import type { Question, QLevel, QType, Difficulty } from '../types';

function q(
  id: string,
  subject: string,
  topic: string,
  level: QLevel,
  type: QType,
  difficulty: Difficulty,
  stem: string,
  options: string[] | undefined,
  answer: number[] | string,
  explanation: string,
  concept: string,
): Question {
  return { id, subject, topic, level, type, difficulty, stem, options, answer, explanation, concept };
}

export const QUESTIONS_1: Question[] = [
  // ---------- ANIMAL BIOTECHNOLOGY ----------
  q('an-1', 'animal-biotechnology', 'an-culture', 'basic', 'mcq', 'easy',
    'Standard incubation conditions for mammalian cell culture are:',
    ['37°C, 5% CO2, pH 7.2–7.4', '25°C, 21% CO2, pH 7.0', '37°C, 0% CO2, pH 6.0', '4°C, 5% CO2, pH 7.4'],
    [0],
    'Mammalian cells grow optimally at body temperature (37°C); 5% CO2 stabilises the bicarbonate buffer at pH ~7.4.',
    'Cell culture conditions'),
  q('an-2', 'animal-biotechnology', 'an-stem', 'basic', 'mcq', 'easy',
    'The four Yamanaka factors used to make iPSCs are:',
    ['Oct4, Sox2, Klf4, c-Myc', 'Oct4, Nanog, Sox2, c-Myc', 'GATA, Sox2, Klf4, c-Myc', 'Oct4, Sox2, Klf4, P53'],
    [0],
    'Yamanaka (2006) reprogrammed fibroblasts using Oct4, Sox2, Klf4 and c-Myc (OSKM).',
    'iPSC reprogramming'),
  q('an-3', 'animal-biotechnology', 'an-lines', 'basic', 'mcq', 'easy',
    'Which contaminant, lacking a cell wall, is NOT cleared by penicillin in cell cultures?',
    ['Mycoplasma', 'Staphylococcus', 'E. coli', 'Bacillus'],
    [0],
    'Mycoplasma has no cell wall, so β-lactams (penicillin) do not work against it.',
    'Culture contamination'),
  q('an-4', 'animal-biotechnology', 'an-media', 'college', 'mcq', 'medium',
    'IMDM medium is classically associated with the culture of:',
    ['Hybridoma and B cells', 'Fibroblasts', 'Yeast', 'Bacterial Lactococcus'],
    [0],
    'IMDM (Iscove’s Modified Dulbecco’s Medium) is commonly used for hybridoma and lymphoid cells.',
    'Culture media selection'),
  q('an-5', 'animal-biotechnology', 'an-mab', 'college', 'mcq', 'medium',
    'In HAT selection of hybridomas, aminopterin blocks which pathway?',
    ['De novo nucleotide synthesis', 'Salvage pathway', 'Fatty acid synthesis', 'Amino acid transport'],
    [0],
    'Aminopterin (a folate antagonist) blocks de novo purine synthesis, so only HGPRT-positive cells (using salvage) survive.',
    'HAT selection logic'),
  q('an-6', 'animal-biotechnology', 'an-mab', 'gate', 'mcq', 'medium',
    'Which step is NOT part of the hybridoma selection phase?',
    ['PEG fusion of spleen cells and myeloma', 'Screening wells by ELISA', 'Growth in HAT medium', 'Limiting dilution cloning'],
    [1],
    'ELISA screening detects antibody production but is a SCREENING step, not part of HAT selection itself (selection only retains HGPRT+ cells).',
    'Hybridoma workflow'),
  q('an-7', 'animal-biotechnology', 'an-transgenics', 'gate', 'mcq', 'medium',
    'The first step to verify that a transgene is expressed (not just integrated) is:',
    ['RT-PCR / Western blot', 'PCR on genomic DNA', 'Southern blot', 'Flow cytometry'],
    [0],
    'PCR/Southern confirm integration; RT-PCR (transcript) and Western blot (protein) confirm expression.',
    'Transgenic verification'),
  q('an-8', 'animal-biotechnology', 'an-models', 'gate', 'mcq', 'easy',
    'The correct order of the 3Rs in animal research ethics is:',
    ['Replace, Reduce, Refine', 'Reduce, Replace, Refine', 'Refine, Reduce, Replace', 'Replace, Refine, Reduce'],
    [0],
    'Replace (avoid animals) → Reduce (fewer animals) → Refine (less suffering) is the accepted sequence.',
    'Research ethics'),
  q('an-9', 'animal-biotechnology', 'an-mab', 'college', 'msq', 'hard',
    'Which of the following are true about monoclonal antibody production by hybridoma technology? (Select all that apply.)',
    ['Parent myeloma cells are HGPRT-deficient', 'PEG is used as the fusogen', 'Only IgM can be produced', 'FACS can be used for single-cell cloning'],
    [0, 1, 3],
    'Myeloma parents are HGPRT−; PEG fuses the cells; any isotype can be produced (not only IgM); FACS sorts single cells for cloning.',
    'Hybridoma technology details'),
  q('an-10', 'animal-biotechnology', 'an-culture', 'gate', 'nat', 'medium',
    'A cell culture doubles every 12 hours. Starting from 1×10^6 cells, how many cells are present after 48 hours? (Express as N × 10^6, give N.)',
    undefined,
    '16',
    '48 h = 4 doublings: 1×2^4 = 16, i.e. 16 × 10^6 cells.',
    'Population doubling arithmetic'),

  // ---------- BIOCHEMISTRY ----------
  q('bio-1', 'biochemistry', 'bio-aa', 'basic', 'mcq', 'easy',
    'Protein concentration by UV absorbance (A280) relies mainly on which residues?',
    ['Tryptophan, tyrosine, phenylalanine', 'Lysine, arginine, histidine', 'Cysteine, methionine', 'Glycine, proline'],
    [0],
    'Aromatic residues (Trp, Tyr, Phe) absorb at 280 nm; this is the basis of the A280 method.',
    'Protein quantification'),
  q('bio-2', 'biochemistry', 'bio-enzymes', 'basic', 'mcq', 'easy',
    'Km is best defined as:',
    ['The substrate concentration at which v = Vmax/2', 'The maximum velocity', 'The enzyme concentration at half rate', 'The dissociation constant of ES, always'],
    [0],
    'Km equals the [S] giving half-maximal velocity; it equals Kd only when kcat << k−1.',
    'Michaelis–Menten kinetics'),
  q('bio-3', 'biochemistry', 'bio-enzymes', 'college', 'mcq', 'medium',
    'A competitive inhibitor affects Michaelis–Menten parameters how?',
    ['Km increases, Vmax unchanged', 'Km unchanged, Vmax decreases', 'Both Km and Vmax decrease', 'Both Km and Vmax increase'],
    [0],
    'Competitive inhibitors raise apparent Km (more substrate needed) but Vmax is reachable at high [S].',
    'Enzyme inhibition'),
  q('bio-4', 'biochemistry', 'bio-enzymes', 'gate', 'nat', 'medium',
    'If v = Vmax/3 when [S] = 2 mM, what is Km (in mM)?',
    undefined,
    '4',
    'v/Vmax = [S]/(Km+[S]) → 1/3 = 2/(Km+2) → Km + 2 = 6 → Km = 4 mM.',
    'Michaelis–Menten calculation'),
  q('bio-5', 'biochemistry', 'bio-energy', 'basic', 'mcq', 'easy',
    'The committed (rate-limiting) step of glycolysis is catalysed by:',
    ['Phosphofructokinase-1 (PFK-1)', 'Hexokinase', 'Pyruvate kinase', 'Enolase'],
    [0],
    'PFK-1 (fructose-6-P → fructose-1,6-bisP) is the main regulatory, committed step of glycolysis.',
    'Glycolysis regulation'),
  q('bio-6', 'biochemistry', 'bio-energy', 'college', 'mcq', 'medium',
    'In modern P/O conventions, how many ATP are generated per NADH oxidised in the ETC?',
    ['2.5', '3', '1.5', '4'],
    [0],
    'Modern values: ~2.5 ATP/NADH and ~1.5 ATP/FADH2 (total 30–32 per glucose).',
    'Oxidative phosphorylation'),
  q('bio-7', 'biochemistry', 'bio-energy', 'gate', 'mcq', 'medium',
    '2,4-Dinitrophenol (DNP) causes weight loss because it:',
    ['Uncouples oxidation from phosphorylation, dissipating energy as heat', 'Inhibits Complex I', 'Blocks pyruvate dehydrogenase', 'Inhibits fatty acid synthesis'],
    [0],
    'DNP is a protonophore: it collapses the proton gradient so ETC runs without ATP synthesis (heat instead).',
    'Chemiosmotic uncoupling'),
  q('bio-8', 'biochemistry', 'bio-sugars', 'college', 'mcq', 'medium',
    'Which disaccharide is NON-reducing?',
    ['Sucrose', 'Lactose', 'Maltose', 'Cellobiose'],
    [0],
    'Sucrose (glucose α1→β2 fructose) has both anomeric carbons involved in the glycosidic bond, so it cannot reduce.',
    'Carbohydrate chemistry'),
  q('bio-9', 'biochemistry', 'bio-nucl', 'gate', 'mcq', 'medium',
    'Deficiency of HGPRT (Lesch–Nyhan syndrome) impairs which pathway?',
    ['Purine salvage', 'Purine de novo synthesis', 'Pyrimidine synthesis', 'Nucleotide degradation'],
    [0],
    'HGPRT converts guanine/hypoxanthine to GMP/IMP — the salvage route; its absence is exploited in HAT selection too.',
    'Nucleotide metabolism'),
  q('bio-10', 'biochemistry', 'bio-reg', 'gate', 'msq', 'hard',
    'Which of the following statements about metabolic regulation are correct? (Select all that apply.)',
    ['PFK-1 and FBPase-1 are reciprocally regulated', 'Malonyl-CoA inhibits CPT-1', 'AMPK activates anabolism when AMP is high', 'Gluconeogenesis bypasses 3 irreversible glycolytic steps'],
    [0, 1, 3],
    'PFK-1/FBPase-1 are the reciprocal glycolysis/gluconeogenesis pair; malonyl-CoA blocks CPT-1 (stopping FA oxidation during synthesis); gluconeogenesis has 4 bypass enzymes for 3 irreversible steps. AMPK activates CATABOLISM, not anabolism.',
    'Metabolic regulation'),

  // ---------- BIOINFORMATICS ----------
  q('inf-1', 'bioinformatics', 'inf-dbs', 'basic', 'mcq', 'easy',
    'In BLAST, the E-value represents:',
    ['The expected number of random matches of score S or better', 'The exact alignment probability', 'The percent identity', 'The number of gaps'],
    [0],
    'E = Kmn·e^(−λS): the number of hits with score ≥ S expected by chance given database size.',
    'BLAST statistics'),
  q('inf-2', 'bioinformatics', 'inf-dbs', 'college', 'mcq', 'medium',
    'BLASTx translates:',
    ['The query nucleotide sequence (6 frames) against a protein database', 'The protein query against a nucleotide database', 'Both query and database', 'Neither; it is for whole genomes'],
    [0],
    'BLASTx: nucleotide query translated in 6 frames vs protein DB. tBLASTn is the reverse (DB translated).',
    'BLAST variants'),
  q('inf-3', 'bioinformatics', 'inf-align', 'basic', 'mcq', 'easy',
    'The Smith–Waterman algorithm performs:',
    ['Local alignment', 'Global alignment', 'Multiple sequence alignment', 'Genome assembly'],
    [0],
    'Smith–Waterman finds the best local match (resets negative scores to zero); Needleman–Wunsch is global.',
    'Alignment algorithms'),
  q('inf-4', 'bioinformatics', 'inf-align', 'college', 'mcq', 'medium',
    'Compared with BLOSUM45, BLOSUM80 is more appropriate for comparing:',
    ['Closely related sequences', 'Very distant sequences', 'Nucleotide sequences', 'Whole genomes'],
    [0],
    'Higher BLOSUM numbers score matches/mismatches derived from closer alignments — use high numbers for close homologues.',
    'Substitution matrices'),
  q('inf-5', 'bioinformatics', 'inf-phylo', 'college', 'nat', 'medium',
    'Two 1000-site sequences differ at 100 positions (p = 0.1). Using the Jukes–Cantor correction, the evolutionary distance d = −(3/4) ln(1 − 4p/3) is approximately (2 decimals):',
    undefined,
    '0.11',
    'd = −0.75 × ln(1 − 0.1333) = −0.75 × ln(0.8667) ≈ −0.75 × (−0.1431) ≈ 0.107 ≈ 0.11.',
    'Phylogenetic distance'),
  q('inf-6', 'bioinformatics', 'inf-motif', 'gate', 'mcq', 'medium',
    'A position-specific scoring matrix (PSSM) score at a position is the log-odds of:',
    ['Observed residue frequency vs background frequency', 'Random vs ordered sequences', 'Match vs mismatch at one site', 'Conserved vs variable columns'],
    [0],
    'PSSM entries are log2(f_observed / f_background) — positive scores mark over-represented residues.',
    'Motif analysis'),
  q('inf-7', 'bioinformatics', 'inf-rnaseq', 'gate', 'mcq', 'medium',
    'The typical threshold for declaring a gene differentially expressed is:',
    ['|log2 fold change| ≥ 1 and adjusted p < 0.05', 'Fold change ≥ 10 with no p-value', 'p < 0.05 with any fold change', '|log2FC| ≥ 0 and p < 0.5'],
    [0],
    'A common, reproducible filter combines biological magnitude (≥2-fold, i.e. |log2FC|≥1) with statistical significance (FDR < 0.05).',
    'RNA-seq analysis'),
  q('inf-8', 'bioinformatics', 'inf-structure', 'gate', 'mcq', 'medium',
    'In AlphaFold2, a per-residue pLDDT of 55 indicates:',
    ['Low confidence', 'Very high confidence', 'Certain accuracy', 'The residue is disordered by definition'],
    [0],
    'pLDDT bands: ≥90 high, 70–90 confident, 50–70 low, <50 very low. 55 is "low confidence".',
    'Structure prediction'),
  q('inf-9', 'bioinformatics', 'inf-align', 'gate', 'nat', 'hard',
    'An alignment has 12 matches (+1 each), 3 mismatches (−1 each) and one gap of length 2 with open cost 2 and extend cost 1 per residue. What is the total score?',
    undefined,
    '6',
    'Gap cost = open + extend×(len−1) = 2 + 1×1 = 3. Total = 12(1) − 3(1) − 3 = 6.',
    'Alignment scoring with affine gaps'),
  q('inf-10', 'bioinformatics', 'inf-phylo', 'college', 'msq', 'hard',
    'Which of the following are correct about phylogenetic methods? (Select all that apply.)',
    ['UPGMA assumes a molecular clock', 'Neighbour-joining does not require a clock', 'Bootstrap values measure clade probability of being true', 'Long-branch attraction affects parsimony'],
    [0, 1, 3],
    'UPGMA is clock-based; NJ is not; bootstrap measures resampling robustness (NOT the probability the clade is true); parsimony is prone to long-branch attraction.',
    'Phylogenetics'),

  // ---------- BIOINSTRUMENTATION ----------
  q('ins-1', 'bioinstrumentation', 'ins-sensors', 'basic', 'mcq', 'easy',
    'The Nernst slope for a pH electrode at 25°C is approximately:',
    ['−59.16 mV per pH unit', '+59.16 mV per pH unit', '−25.7 mV per pH unit', '−118 mV per pH unit'],
    [0],
    'E = E° − (2.303RT/F)pH; at 25°C the slope is ≈ −59.16 mV per pH unit.',
    'pH sensing'),
  q('ins-2', 'bioinstrumentation', 'ins-sensors', 'college', 'mcq', 'medium',
    'A Clark (polarographic) dissolved-oxygen probe works by:',
    ['O2 reduction at a cathode producing a measurable current', 'Fluorescence quenching of a dye', 'Elastic light scattering', 'O2 absorption by a polymer'],
    [0],
    'Clark probes are amperometric: O2 diffuses through a membrane and is reduced at the cathode, generating current proportional to DO.',
    'DO measurement'),
  q('ins-3', 'bioinstrumentation', 'ins-signals', 'basic', 'mcq', 'easy',
    'To avoid aliasing, the sampling frequency must be:',
    ['Greater than twice the highest signal frequency', 'Equal to the highest frequency', 'Half the highest frequency', 'Independent of signal frequency'],
    [0],
    'Nyquist criterion: fs > 2fmax. Sampling at or below the limit folds high frequencies into the band.',
    'Signal acquisition'),
  q('ins-4', 'bioinstrumentation', 'ins-spectro', 'college', 'nat', 'medium',
    'A solution shows A260 = 0.8. Assuming A260 = 1.0 corresponds to 50 µg/mL dsDNA, the concentration is (µg/mL):',
    undefined,
    '40',
    'Concentration = 0.8 × 50 = 40 µg/mL (Beer–Lambert linearity at this absorbance).',
    'Nucleic acid quantification'),
  q('ins-5', 'bioinstrumentation', 'ins-spectro', 'gate', 'mcq', 'medium',
    'A260/A280 ratio of a DNA preparation of about 1.5 suggests:',
    ['Protein contamination', 'Pure DNA', 'RNA contamination only', 'Salt contamination'],
    [0],
    'Pure dsDNA ≈ 1.8; a lower ratio (~1.5) indicates protein (or phenol) contamination.',
    'Nucleic acid purity'),
  q('ins-6', 'bioinstrumentation', 'ins-chromo', 'college', 'mcq', 'medium',
    'In size-exclusion chromatography, the molecule that elutes FIRST is generally:',
    ['The largest (excluded from pores)', 'The smallest', 'The most charged', 'The most hydrophobic'],
    [0],
    'Large molecules are excluded from the bead pores and take the shorter path, eluting first.',
    'Chromatography principles'),
  q('ins-7', 'bioinstrumentation', 'ins-chromo', 'gate', 'nat', 'medium',
    'Two peaks have retention times 10.0 and 11.0 min and baseline widths 0.4 and 0.6 min. The resolution Rs = 2(tR2 − tR1)/(w1 + w2) equals:',
    undefined,
    '2.0',
    'Rs = 2(11.0 − 10.0)/(0.4 + 0.6) = 2/1.0 = 2.0 (baseline separation ≥ 1.5 is generally adequate).',
    'Chromatographic resolution'),
  q('ins-8', 'bioinstrumentation', 'ins-assays', 'gate', 'mcq', 'medium',
    'In a competitive ELISA, the signal intensity is:',
    ['Inversely proportional to analyte concentration', 'Directly proportional to analyte concentration', 'Independent of analyte', 'Proportional to analyte squared'],
    [0],
    'More analyte competes away labelled antigen/antibody → less bound label → lower signal (inverse relationship).',
    'Immunoassay formats'),
  q('ins-9', 'bioinstrumentation', 'ins-feedback', 'gate', 'mcq', 'medium',
    'In a PID controller, the term that eliminates steady-state offset is the:',
    ['Integral term', 'Proportional term', 'Derivative term', 'Feedforward term'],
    [0],
    'Pure proportional control leaves a residual error; the integral action accumulates error until offset is removed.',
    'Process control'),
  q('ins-10', 'bioinstrumentation', 'ins-sensors', 'gate', 'msq', 'hard',
    'Which statements about biosensors are correct? (Select all that apply.)',
    ['A biosensor pairs a biological recognition element with a transducer', 'SPR measures binding kinetics label-free', 'First-generation amperometric sensors use direct electron transfer without a mediator', 'Glucose oxidase sensors measure O2 consumption'],
    [0, 1, 3],
    'Biosensor = recognition + transducer; SPR is label-free kinetic; glucose oxidase consumes O2 (amperometric). First-generation sensors DO use a mediator or the O2 product; direct electron transfer characterises third-generation sensors.',
    'Biosensor architectures'),

  // ---------- BIOREACTION ENGINEERING ----------
  q('bae-1', 'bioreaction-engineering', 'bae-kinetics', 'basic', 'mcq', 'easy',
    'The doubling time td of an organism growing with specific growth rate µ is:',
    ['ln2/µ', 'µ/ln2', '2µ', '1/µ'],
    [0],
    'From X = X0·e^(µt), setting X/X0 = 2 gives td = ln2/µ.',
    'Growth kinetics'),
  q('bae-2', 'bioreaction-engineering', 'bae-kinetics', 'college', 'mcq', 'medium',
    'In Monod kinetics, Ks equals the substrate concentration at which:',
    ['µ = µmax/2', 'µ = µmax', 'Growth stops', 'Substrate is fully consumed'],
    [0],
    'Ks is the half-saturation constant: µ = µmax·S/(Ks+S) = µmax/2 when S = Ks.',
    'Monod equation'),
  q('bae-3', 'bioreaction-engineering', 'bae-cstr', 'basic', 'mcq', 'easy',
    'At steady state in an ideal CSTR bioreactor, the dilution rate D equals:',
    ['The specific growth rate µ', 'The substrate concentration S', 'The biomass concentration X', 'The yield Yx/s'],
    [0],
    'Steady state: cells leaving (D·X) must equal cells growing (µ·X), so µ = D.',
    'CSTR steady state'),
  q('bae-4', 'bioreaction-engineering', 'bae-cstr', 'gate', 'nat', 'medium',
    'A chemostat has µmax = 0.5 h⁻¹, Ks = 1 g/L, S0 = 10 g/L, Yx/s = 0.5 g/g, D = 0.4 h⁻¹. The steady-state substrate concentration S (g/L) is:',
    undefined,
    '4',
    'At steady state µ = D = µmax·S/(Ks+S) → S = Ks·D/(µmax − D) = 1×0.4/0.1 = 4 g/L.',
    'CSTR design calculation'),
  q('bae-5', 'bioreaction-engineering', 'bae-cstr', 'gate', 'mcq', 'medium',
    'Washout in a chemostat occurs when:',
    ['D exceeds µmax', 'D is much less than µmax', 'Yx/s is very high', 'S0 is very low'],
    [0],
    'If D > µmax, cells are removed faster than they can divide; X → 0 and S → S0.',
    'Chemostat operation'),
  q('bae-6', 'bioreaction-engineering', 'bae-oxygen', 'college', 'mcq', 'medium',
    'The oxygen transfer rate (OTR) in an aerated bioreactor is given by:',
    ['kLa(C* − CL)', 'kL(C* + CL)', 'qO2/C*', 'P/V × CL'],
    [0],
    'OTR = kLa(C* − CL): kLa is the volumetric transfer coefficient, C* saturation and CL the working DO concentration.',
    'Oxygen transfer'),
  q('bae-7', 'bioreaction-engineering', 'bae-oxygen', 'gate', 'mcq', 'medium',
    'Increasing the viscosity of the fermentation broth generally:',
    ['Decreases kLa', 'Increases kLa', 'Has no effect on kLa', 'Increases C*'],
    [0],
    'Higher viscosity reduces bubble dispersion and diffusion, lowering the volumetric oxygen transfer coefficient.',
    'kLa determinants'),
  q('bae-8', 'bioreaction-engineering', 'bae-batch', 'gate', 'mcq', 'medium',
    'A product formed only during the stationary phase (e.g., penicillin) is a:',
    ['Secondary metabolite', 'Primary metabolite', 'Growth-associated product', 'Essential metabolite'],
    [0],
    'Secondary metabolites are non-growth-linked, made in stationary phase (antibiotics, pigments).',
    'Metabolite classification'),
  q('bae-9', 'bioreaction-engineering', 'bae-cell-bioreactors', 'gate', 'mcq', 'medium',
    'The Rushton turbine impeller is characterised by:',
    ['Radial flow and relatively high shear', 'Axial flow and low shear', 'No flow; gas-only mixing', 'Pulse flow'],
    [0],
    'Rushton (flat-blade, baffled) pushes fluid radially outward with high shear — good for aerobic bacteria, too harsh for many mammalian cells.',
    'Impeller selection'),
  q('bae-10', 'bioreaction-engineering', 'bae-batch', 'gate', 'nat', 'medium',
    'A batch culture grows exponentially with µ = 0.25 h⁻¹ from 1 g/L to 8 g/L. The required growth time (h) is:',
    undefined,
    '8.3',
    't = (1/µ)·ln(X2/X1) = (1/0.25)·ln(8) = 4 × 2.079 ≈ 8.32 h ≈ 8.3 h.',
    'Batch growth time'),

  // ---------- CELL BIOLOGY ----------
  q('cel-1', 'cell-biology', 'cel-membrane', 'basic', 'mcq', 'easy',
    'The Na+/K+ ATPase moves, per ATP hydrolysed:',
    ['3 Na+ out, 2 K+ in', '2 Na+ out, 3 K+ in', '3 Na+ in, 2 K+ out', '1 Na+ out, 1 K+ in'],
    [0],
    'The pump exports 3 Na+ and imports 2 K+ per ATP — electrogenic, setting the resting potential.',
    'Membrane transport'),
  q('cel-2', 'cell-biology', 'cel-cycle', 'college', 'mcq', 'medium',
    'The complex that triggers entry into mitosis (M phase) is:',
    ['Cyclin B + CDK1 (MPF)', 'Cyclin D + CDK4', 'Cyclin A + CDK2 alone', 'p53 + p21'],
    [0],
    'MPF (maturation promoting factor) = cyclin B–CDK1 drives G2→M transition.',
    'Cell cycle control'),
  q('cel-3', 'cell-biology', 'cel-cycle', 'gate', 'mcq', 'medium',
    'DNA damage in G1 activates p53, which then:',
    ['Induces p21 to inhibit CDKs and arrest the cycle', 'Directly degrades cyclin B', 'Activates APC/C immediately', 'Inhibits Rb to push into S phase'],
    [0],
    'p53 upregulates p21 (a CDK inhibitor), halting the cycle for repair; severe damage leads to apoptosis.',
    'DNA damage response'),
  q('cel-4', 'cell-biology', 'cel-organelles', 'college', 'mcq', 'medium',
    'Vesicles carrying protein from the ER to the Golgi are coated with:',
    ['COPII', 'COPI', 'Clathrin', 'Caveolin'],
    [0],
    'COPII coats mediate forward (ER→Golgi) transport; COPI mediates retrograde (Golgi→ER) retrieval.',
    'Vesicle trafficking'),
  q('cel-5', 'cell-biology', 'cel-signaling', 'gate', 'mcq', 'medium',
    'The Gαs protein activates which second-messenger pathway?',
    ['Adenylyl cyclase → cAMP → PKA', 'Phospholipase C → IP3 + DAG', 'Inhibition of adenylyl cyclase', 'Direct activation of PI3K'],
    [0],
    'Gαs stimulates adenylyl cyclase (cAMP/PKA); Gαq activates PLC (IP3/DAG); Gαi inhibits adenylyl cyclase.',
    'GPCR signalling'),
  q('cel-6', 'cell-biology', 'cel-signaling', 'gate', 'mcq', 'hard',
    'The correct order in the classical RTK growth pathway is:',
    ['RTK → RAS → RAF → MEK → ERK', 'RTK → MEK → RAF → RAS → ERK', 'RAS → RTK → RAF → MEK → ERK', 'RTK → RAF → RAS → MEK → ERK'],
    [0],
    'Receptor dimerisation → RAS activation → RAF → MEK → ERK (MAPK cascade) → transcription factors.',
    'MAPK cascade'),
  q('cel-7', 'cell-biology', 'cel-death', 'college', 'mcq', 'medium',
    'Cytochrome c release from mitochondria activates which initiator caspase?',
    ['Caspase-9', 'Caspase-8', 'Caspase-3', 'Caspase-6'],
    [0],
    'Cytochrome c + Apaf-1 + pro-caspase-9 form the apoptosome → caspase-9 → executioner caspases (3/6/7). Caspase-8 is the extrinsic initiator.',
    'Apoptosis'),
  q('cel-8', 'cell-biology', 'cel-death', 'gate', 'mcq', 'medium',
    'Apoptosis is best described as:',
    ['Programmed, non-inflammatory cell death', 'Uncontrolled, inflammatory cell swelling', 'Always due to DNA damage', 'Cell division failure'],
    [0],
    'Apoptosis is controlled and non-inflammatory (phagocytosed quietly); necrosis is the inflammatory, uncontrolled counterpart.',
    'Cell death types'),
  q('cel-9', 'cell-biology', 'cel-cytoskeleton', 'gate', 'mcq', 'medium',
    'Kinesin and dynein move cargoes along microtubules toward:',
    ['The plus end and the minus end, respectively', 'The minus end and the plus end, respectively', 'Both the plus end', 'Both the minus end'],
    [0],
    'Conventional kinesin walks toward the (+) end (cell periphery); dynein toward the (−) end (centrosome).',
    'Motor proteins'),
  q('cel-10', 'cell-biology', 'cel-proteostasis', 'gate', 'mcq', 'medium',
    'In the ubiquitin–proteasome pathway, substrate SPECIFICITY is provided mainly by:',
    ['E3 ligases', 'E1 activating enzymes', 'E2 conjugating enzymes', 'The 20S core'],
    [0],
    'E1 activates ubiquitin and E2 carries it; E3 ligases recognise specific substrates and catalyse transfer.',
    'Protein degradation'),
];
