import type { Question, QLevel, QType, Difficulty } from '../types';

function q(
  id: string,
  subject: string,
  topic: string,
  level: QLevel,
  type: QType,
  difficulty: Difficulty,
  stem: string,
  options: string[] | undefined,
  answer: number[] | string,
  explanation: string,
  concept: string,
): Question {
  return { id, subject, topic, level, type, difficulty, stem, options, answer, explanation, concept };
}

export const QUESTIONS_2: Question[] = [
  // ---------- ENVIRONMENTAL BIOTECH ----------
  q('env-1', 'environmental-biotechnology', 'env-bioremediation', 'basic', 'mcq', 'easy',
    'Enhancing the growth of NATIVE microorganisms to clean a pollutant is called:',
    ['Biostimulation', 'Bioaugmentation', 'Phytoremediation', 'Biosorption'],
    [0],
    'Biostimulation feeds the existing community (nutrients/O2); bioaugmentation adds specialised strains.',
    'Bioremediation strategies'),
  q('env-2', 'environmental-biotechnology', 'env-bioremediation', 'gate', 'mcq', 'medium',
    'Which of the following pollutants CANNOT be destroyed by biodegradation?',
    ['Heavy metals (e.g., mercury, chromium)', 'Petroleum hydrocarbons', 'Chlorinated solvents', 'Pesticides (some)'],
    [0],
    'Metals cannot be degraded — they can only be transformed (e.g., Hg methylation), immobilised or removed.',
    'Metal bioremediation limit'),
  q('env-3', 'environmental-biotechnology', 'env-wastewater', 'college', 'mcq', 'medium',
    'Nitrification in activated sludge is carried out by:',
    ['Autotrophic bacteria under AEROBIC conditions', 'Heterotrophs under anaerobic conditions', 'Archaea under anoxic conditions', 'Fungi in the clarifier'],
    [0],
    'Nitrosomonas/Nitrobacter are chemoautotrophs oxidising NH3→NO2→NO3 aerobically; they are slow growers.',
    'Nitrification'),
  q('env-4', 'environmental-biotechnology', 'env-wastewater', 'gate', 'mcq', 'medium',
    'Denitrification requires which conditions?',
    ['Anoxic: no dissolved O2 but nitrate present', 'Strictly anaerobic: no O2 and no nitrate', 'Aerobic with high O2', 'Any oxygen level'],
    [0],
    'Denitrifiers use NO3− as the electron acceptor only when O2 is absent (anoxic) — a classic condition distinction.',
    'Denitrification conditions'),
  q('env-5', 'environmental-biotechnology', 'env-biopesticides', 'gate', 'mcq', 'medium',
    'Bt (Bacillus thuringiensis) Cry toxins become active because of:',
    ['Alkaline pH of the insect midgut', 'Acidic pH of the mammalian stomach', 'Ultraviolet light', 'Heat denaturation'],
    [0],
    'Cry prototoxins are activated at the alkaline pH of the insect midgut, bind receptors and form pores — harmless in acidic mammalian stomach.',
    'Bt mechanism'),
  q('env-6', 'environmental-biotechnology', 'env-biodegradation', 'college', 'mcq', 'medium',
    'PETase, the enzyme that initiates PET degradation, was discovered in:',
    ['Ideonella sakaiensis', 'E. coli', 'Pseudomonas putida', 'Aspergillus niger'],
    [0],
    'I. sakaiensis (2016) produces PETase; full PET mineralisation also needs MHETase and terephthalate oxidisers.',
    'Plastic degradation'),
  q('env-7', 'environmental-biotechnology', 'env-climate', 'gate', 'mcq', 'medium',
    'Methane production in anaerobic digesters is performed by:',
    ['Archaea (methanogens)', 'Gram-negative bacteria', 'Fungi', 'Protozoa'],
    [0],
    'Methanogens are archaea — the methanogenesis step of anaerobic digestion is performed by the Archaea domain.',
    'Anaerobic digestion'),
  q('env-8', 'environmental-biotechnology', 'env-wastewater', 'gate', 'nat', 'medium',
    'A STP receives BOD = 200 mg/L and discharges BOD = 20 mg/L. The BOD removal percentage is:',
    undefined,
    '90',
    'Removal = (200 − 20)/200 × 100 = 90% — typical secondary treatment performance.',
    'BOD removal'),
  q('env-9', 'environmental-biotechnology', 'env-biodiversity', 'gate', 'mcq', 'medium',
    'The standard DNA barcoding marker for ANIMALS is:',
    ['COI (cytochrome c oxidase I)', 'rbcL', '16S rRNA', 'ITS'],
    [0],
    'COI is the animal barcode; plants use rbcL/matK; 16S targets bacteria/archaea; ITS is a fungal barcode.',
    'DNA barcoding'),
  q('env-10', 'environmental-biotechnology', 'env-bioremediation', 'college', 'msq', 'hard',
    'Which of the following statements about bioremediation are correct? (Select all that apply.)',
    ['Biostimulation uses native microbes', 'Cometabolism requires a primary carbon source', 'White-rot fungi degrade PAHs via lignin peroxidases', 'Mercury can be completely mineralised by bacteria'],
    [0, 1, 2],
    'Biostimulation feeds natives; cometabolism needs a co-substrate; white-rot peroxidases attack lignin-like PAHs. Mercury is transformed (methylated), never mineralised.',
    'Bioremediation concepts'),

  // ---------- GENETICS ----------
  q('gen-1', 'genetics-evolution', 'gen-mendel', 'basic', 'mcq', 'easy',
    'AaBb × AaBb (independent assortment, complete dominance) gives the phenotypic ratio:',
    ['9:3:3:1', '3:1', '1:2:1', '1:1:1:1'],
    [0],
    'The dihybrid cross of two double heterozygotes yields 9:3:3:1 phenotypically.',
    'Dihybrid ratios'),
  q('gen-2', 'genetics-evolution', 'gen-mendel', 'gate', 'nat', 'medium',
    'Two plants are AaBb. What is the probability their offspring is AAbb? (Give the value as a fraction over 16, i.e. the numerator.)',
    undefined,
    '1',
    'P(AA) = 1/4 and P(bb) = 1/4; independent → 1/16. Numerator = 1.',
    'Product rule in genetics'),
  q('gen-3', 'genetics-evolution', 'gen-linkage', 'college', 'nat', 'medium',
    'In a test cross, 180 recombinant progeny are observed out of 2000 total. The recombination frequency (%) is:',
    undefined,
    '9',
    'RF = 180/2000 × 100 = 9% → genes are 9 cM apart.',
    'Recombination frequency'),
  q('gen-4', 'genetics-evolution', 'gen-linkage', 'gate', 'mcq', 'medium',
    'The maximum observable recombination frequency between two loci is:',
    ['50%', '100%', '25%', '75%'],
    [0],
    'RF caps at 50% — beyond that, crossovers produce no net excess of recombinants and loci behave unlinked.',
    'Linkage limits'),
  q('gen-5', 'genetics-evolution', 'gen-mutation', 'college', 'mcq', 'medium',
    'Xeroderma pigmentosum results from defective:',
    ['Nucleotide excision repair', 'Base excision repair', 'Mismatch repair', 'Homologous recombination'],
    [0],
    'XP cells cannot excise UV-induced pyrimidine dimers (NER defect), causing extreme UV sensitivity and skin cancer.',
    'DNA repair and disease'),
  q('gen-6', 'genetics-evolution', 'gen-popgen', 'basic', 'mcq', 'easy',
    'Under Hardy–Weinberg equilibrium, if q² = 0.04, then the carrier frequency 2pq is approximately:',
    ['0.27', '0.08', '0.32', '0.24'],
    [2],
    'q = √0.04 = 0.2; p = 0.8; 2pq = 2 × 0.8 × 0.2 = 0.32.',
    'Hardy–Weinberg'),
  q('gen-7', 'genetics-evolution', 'gen-popgen', 'gate', 'nat', 'medium',
    'A recessive disorder affects 1 in 2500 people. Assuming HWE, how many carriers are there per 1000 people?',
    undefined,
    '39.2',
    'q = 1/50 = 0.02, p = 0.98; carriers = 2pq = 2 × 0.98 × 0.02 = 0.0392 → 39.2 per 1000 people.',
    'Carrier frequency'),
  q('gen-8', 'genetics-evolution', 'gen-evolution', 'gate', 'mcq', 'medium',
    'Stabilising selection acts on a trait by:',
    ['Favouring intermediate phenotypes and reducing variance', 'Shifting the mean in one direction', 'Favouring both extremes', 'Increasing mutation rate'],
    [0],
    'Stabilising selection selects against extremes (e.g. birth weight), reducing variation around the optimum.',
    'Selection types'),
  q('gen-9', 'genetics-evolution', 'gen-molevol', 'gate', 'mcq', 'medium',
    'A protein-coding site with dN/dS (ω) of 0.1 is under:',
    ['Strong purifying selection', 'Positive selection', 'Neutral evolution', 'Balancing selection'],
    [0],
    'ω < 1: nonsynonymous changes are removed (purifying); ω = 1 neutral; ω > 1 positive (adaptive).',
    'Molecular evolution'),
  q('gen-10', 'genetics-evolution', 'gen-quant', 'gate', 'nat', 'medium',
    'A crop trait has narrow-sense heritability h² = 0.6. The selection differential S is 50 kg/ha. The expected response R (kg/ha) is:',
    undefined,
    '30',
    'Breeder’s equation: R = h² × S = 0.6 × 50 = 30 kg/ha.',
    'Breeder’s equation'),

  // ---------- IMMUNOLOGY ----------
  q('imm-1', 'immunology', 'imm-basics', 'basic', 'mcq', 'easy',
    'The complement membrane attack complex (MAC) is formed by:',
    ['C5b–C9', 'C1–C4', 'C3 only', 'C5a only'],
    [0],
    'C5b–C9 assemble into the MAC pore that lytes target cells; C3a/C5a are anaphylatoxins.',
    'Complement'),
  q('imm-2', 'immunology', 'imm-antibodies', 'basic', 'mcq', 'easy',
    'The first antibody produced in a primary immune response is:',
    ['IgM', 'IgG', 'IgA', 'IgE'],
    [0],
    'IgM appears first (pentamer, high avidity, poor affinity); IgG dominates secondary responses.',
    'Immune response kinetics'),
  q('imm-3', 'immunology', 'imm-antibodies', 'college', 'mcq', 'medium',
    'Which immunoglobulin crosses the placenta?',
    ['IgG', 'IgA', 'IgM', 'IgE'],
    [0],
    'Only IgG is transported to the fetus via the neonatal Fc receptor (FcRn), providing passive immunity.',
    'Immunoglobulin classes'),
  q('imm-4', 'immunology', 'imm-response', 'gate', 'mcq', 'medium',
    'CD8+ cytotoxic T cells recognise antigen presented on:',
    ['MHC class I', 'MHC class II', 'Free antigen', 'CD1'],
    [0],
    'MHC I (all nucleated cells, endogenous antigen) → CD8; MHC II (APCs, exogenous antigen) → CD4.',
    'MHC restriction'),
  q('imm-5', 'immunology', 'imm-response', 'gate', 'mcq', 'medium',
    'T-cell activation requires antigen recognition PLUS co-stimulation. Without co-stimulation, the T cell becomes:',
    ['Anergic', 'Anaphylactic', 'Autoreactive', 'Activated'],
    [0],
    'Signal 1 (TCR–MHC) without signal 2 (CD28–B7) leads to anergy (unresponsiveness), a peripheral tolerance mechanism.',
    'T-cell activation'),
  q('imm-6', 'immunology', 'imm-hypersensitivity', 'gate', 'mcq', 'medium',
    'Rheumatoid arthritis is classified as which type of hypersensitivity?',
    ['Type IV (T-cell mediated)', 'Type II', 'Type III', 'Type I'],
    [0],
    'RA is Type IV: T cells and macrophages drive synovial inflammation — a famous exception to "arthritis = immune complex".',
    'Hypersensitivity classification'),
  q('imm-7', 'immunology', 'imm-vaccines', 'college', 'nat', 'medium',
    'A pathogen has R0 = 5. The herd immunity threshold (percentage, 1 decimal) is:',
    undefined,
    '80.0',
    'Pc = 1 − 1/R0 = 1 − 1/5 = 0.8 → 80%.',
    'Herd immunity'),
  q('imm-8', 'immunology', 'imm-auto', 'gate', 'mcq', 'medium',
    'Bruton’s agammaglobulinaemia (BTK mutation) results in absence of:',
    ['B cells and antibodies (T cells normal)', 'T cells', 'NK cells', 'Both T and B cells'],
    [0],
    'BTK is required for B-cell development; T cells are normal. Recurrent bacterial infections begin after maternal IgG wanes (~6 months).',
    'Primary immunodeficiency'),
  q('imm-9', 'immunology', 'imm-mhc', 'gate', 'mcq', 'medium',
    'MHC class I molecules are expressed on:',
    ['All nucleated cells', 'Professional APCs only', 'Red blood cells only', 'Platelets only'],
    [0],
    'MHC I is on virtually all nucleated cells (endogenous antigen presentation); RBCs and platelets lack it.',
    'MHC expression'),
  q('imm-10', 'immunology', 'imm-hypersensitivity', 'college', 'msq', 'hard',
    'Which pairings of hypersensitivity type and example are CORRECT? (Select all that apply.)',
    ['Type I — anaphylaxis', 'Type II — ABO transfusion reaction', 'Type III — serum sickness', 'Type IV — hay fever'],
    [0, 1, 2],
    'I = IgE immediate (anaphylaxis); II = Ab vs cell surface (ABO transfusion); III = complexes (serum sickness). Hay fever is Type I, not IV.',
    'Hypersensitivity examples'),

  // ---------- MICROBIAL BIOTECH ----------
  q('mib-1', 'microbial-biotechnology', 'mib-fermentation', 'basic', 'mcq', 'easy',
    'Ethanol produced by yeast is a:',
    ['Primary metabolite', 'Secondary metabolite', 'Vitamin', 'Hormone'],
    [0],
    'Ethanol is growth-linked (exponential phase) — a primary metabolite; antibiotics are secondary.',
    'Metabolite classes'),
  q('mib-2', 'microbial-biotechnology', 'mib-fermentation', 'college', 'mcq', 'medium',
    'Penicillin production by Penicillium is typically:',
    ['Stationary phase (secondary metabolite)', 'Exponential phase', 'Lag phase', 'Death phase'],
    [0],
    'Penicillin is a secondary metabolite — made after growth slows, classically in fed-batch with precursor feeding.',
    'Antibiotic production'),
  q('mib-3', 'microbial-biotechnology', 'mib-antibiotics', 'gate', 'mcq', 'medium',
    'Chloramphenicol inhibits protein synthesis by binding the:',
    ['50S ribosomal subunit', '30S ribosomal subunit', '70S initiator tRNA', 'RNA polymerase'],
    [0],
    'Chloramphenicol blocks peptidyl transferase at the 50S; macrolides and clindamycin share this site.',
    'Antibiotic targets'),
  q('mib-4', 'microbial-biotechnology', 'mib-antibiotics', 'gate', 'mcq', 'medium',
    'The main industrial genus producing most classical antibiotics is:',
    ['Streptomyces', 'Bacillus', 'E. coli', 'Saccharomyces'],
    [0],
    'Soil actinomycetes, especially Streptomyces, produce the majority of natural antibiotics (streptomycin, tetracycline, erythromycin).',
    'Antibiotic producers'),
  q('mib-5', 'microbial-biotechnology', 'mib-strains', 'college', 'mcq', 'medium',
    'To accumulate an amino acid in C. glutamicate, the classical strategy combines auxotrophy with:',
    ['Feedback resistance of the regulatory enzyme', 'Deletion of the entire pathway', 'Reducing plasmid copy number', 'Removing the membrane'],
    [0],
    'Auxotrophy forces flux through the pathway; feedback resistance stops the end-product from shutting it down — both are needed.',
    'Strain improvement'),
  q('mib-6', 'microbial-biotechnology', 'mib-metabolites', 'gate', 'mcq', 'medium',
    'Cellulose hydrolysis to glucose requires which combination of enzymes?',
    ['Endoglucanase + exoglucanase + β-glucosidase', 'Only amylase', 'Only pectinase', 'Only lipase'],
    [0],
    'Cellulase is a system: C1/exo enzymes release cellobiose, which β-glucosidase converts to glucose — all three are needed.',
    'Enzyme systems'),
  q('mib-7', 'microbial-biotechnology', 'mib-mfc', 'gate', 'mcq', 'medium',
    'In a microbial fuel cell, the ANODE compartment must be:',
    ['Anaerobic (no O2)', 'Aerobic', 'Filled with oxygen', 'Sterile'],
    [0],
    'Exoelectrogenic bacteria oxidise substrate at the anode anaerobically, donating electrons to the electrode; O2 is reduced at the cathode.',
    'MFC design'),
  q('mib-8', 'microbial-biotechnology', 'mib-metabolic', 'college', 'mcq', 'medium',
    'The DBTL cycle in metabolic engineering stands for:',
    ['Design–Build–Test–Learn', 'Decode–Breed–Transform–Launch', 'Detect–Bind–Transfer–Ligate', 'Deletion–Biosynthesis–Testing–Longevity'],
    [0],
    'DBTL (design–build–test–learn) is the iterative loop that drives modern strain engineering.',
    'Metabolic engineering'),
  q('mib-9', 'microbial-biotechnology', 'mib-bioprocessing', 'gate', 'mcq', 'medium',
    'For a secreted recombinant antibody, the largest share of cost of goods is usually:',
    ['Downstream processing', 'Raw building materials', 'Staffing', 'Raw substrate'],
    [0],
    'Purification, viral clearance and formulation often consume 50–80% of COGS for high-value proteins.',
    'Bioprocess economics'),
  q('mib-10', 'microbial-biotechnology', 'mib-antibiotics', 'gate', 'msq', 'hard',
    'Which antibiotics inhibit the 30S ribosomal subunit? (Select all that apply.)',
    ['Tetracycline', 'Aminoglycosides', 'Chloramphenicol', 'Erythromycin'],
    [0, 1],
    'Tetracycline and aminoglycosides target 30S (entry/misreading); chloramphenicol and erythromycin target 50S.',
    'Ribosome-targeting antibiotics'),

  // ---------- MICROBIOLOGY ----------
  q('mic-1', 'microbiology', 'mic-physiology', 'basic', 'mcq', 'easy',
    'Organisms that thrive optimally at 45–80°C are called:',
    ['Thermophiles', 'Psychrophiles', 'Mesophiles', 'Halophiles'],
    [0],
    'Thermophiles prefer 45–80°C (Taq comes from the hyperthermophile T. aquaticus); mesophiles ~20–45°C.',
    'Temperature classes'),
  q('mic-2', 'microbiology', 'mic-viruses', 'basic', 'mcq', 'easy',
    'A virus particle contains:',
    ['DNA or RNA, never both', 'Always both DNA and RNA', 'Only DNA', 'Only protein, no nucleic acid'],
    [0],
    'Viruses carry a single type of genome — DNA or RNA (with a few rare exceptions outside the core syllabus).',
    'Virus basics'),
  q('mic-3', 'microbiology', 'mic-viruses', 'college', 'mcq', 'medium',
    'HIV is a retrovirus because it encodes:',
    ['Reverse transcriptase (RNA → DNA)', 'DNA ligase', 'Helicase', 'Integrase only'],
    [0],
    'Retroviruses reverse-transcribe their RNA genome to DNA (provirus) for integration — reverse transcriptase is the hallmark.',
    'Retroviruses'),
  q('mic-4', 'microbiology', 'mic-pathogenicity', 'gate', 'mcq', 'medium',
    'Endotoxin is best described as:',
    ['Lipid A of LPS in the OUTER membrane of Gram-negative bacteria', 'A secreted A-B exotoxin', 'A viral capsid protein', 'A fungal chitin fragment'],
    [0],
    'Endotoxin (LPS) is a membrane component released on lysis; exotoxins are actively secreted proteins.',
    'Toxins'),
  q('mic-5', 'microbiology', 'mic-pathogenicity', 'gate', 'mcq', 'medium',
    'Superantigens (e.g., TSST-1) cause disease by:',
    ['Cross-linking MHC II and TCR, causing massive cytokine release', 'Blocking ribosomes', 'Degrading DNA', 'Inhibiting complement'],
    [0],
    'Superantigens bypass normal processing: they bridge MHC II and TCR non-specifically, activating ~20% of T cells → cytokine storm.',
    'Superantigen mechanism'),
  q('mic-6', 'microbiology', 'mic-sterilization', 'gate', 'nat', 'medium',
    'A sterilisation step has D = 2 min at 121°C. Starting from 10^6 cells, how many minutes are needed for a 4-log (99.99%) reduction?',
    undefined,
    '8',
    '4-log = 4 decimal reductions = 4 × D = 4 × 2 = 8 min.',
    'D-value calculations'),
  q('mic-7', 'microbiology', 'mic-sterilization', 'gate', 'mcq', 'medium',
    'The biological indicator used to validate autoclave performance is:',
    ['Bacillus stearothermophilus spores', 'Staphylococcus aureus', 'E. coli cells', 'Saccharomyces yeast'],
    [0],
    'B. stearothermophilus spores are the most heat-resistant common contaminant — the autoclave validation standard.',
    'Sterilisation validation'),
  q('mic-8', 'microbiology', 'mic-biofilm', 'college', 'mcq', 'medium',
    'Persister cells in a biofilm are best described as:',
    ['Dormant, phenotypically tolerant (not genetically resistant)', 'Cells with a resistance mutation', 'Spores with a coat', 'Virulent variants'],
    [0],
    'Persisters survive via dormancy/tolerance; resistance implies heritable genetic change. Both coexist in chronic infections.',
    'Biofilm physiology'),
  q('mic-9', 'microbiology', 'mic-ecology', 'gate', 'mcq', 'medium',
    'The standard phylogenetic marker for bacteria and archaea is the:',
    ['16S rRNA gene', '18S rRNA gene', 'COI gene', 'rbcL gene'],
    [0],
    '16S rRNA defines bacterial/archaeal phylogeny; 18S is for eukaryotes; COI/rbcL are barcoding genes.',
    'Microbial phylogeny'),
  q('mic-10', 'microbiology', 'mic-fungi', 'gate', 'mcq', 'medium',
    'The fungal cell wall is primarily composed of:',
    ['Chitin', 'Peptidoglycan', 'Cellulose', 'Collagen'],
    [0],
    'Fungi have chitin walls; bacteria have peptidoglycan; plants have cellulose.',
    'Fungal structure'),

  // ---------- MOLECULAR BIOLOGY ----------
  q('mol-1', 'molecular-biology', 'mol-replication', 'basic', 'mcq', 'easy',
    'DNA replication is called semi-conservative because each new duplex contains:',
    ['One old and one new strand', 'Two new strands', 'Two old strands', 'Alternating old and new segments'],
    [0],
    'Meselson–Stahl (1958) showed each daughter DNA keeps one parental strand — the semi-conservative model.',
    'Replication models'),
  q('mol-2', 'molecular-biology', 'mol-replication', 'college', 'mcq', 'medium',
    'Okazaki fragments are synthesised on the:',
    ['Lagging strand', 'Leading strand', 'Template strand', 'Primer'],
    [0],
    'Because polymerase only extends 5′→3′, the strand antiparallel to fork movement is copied discontinuously (Okazaki fragments).',
    'Replication mechanics'),
  q('mol-3', 'molecular-biology', 'mol-transcription', 'gate', 'mcq', 'medium',
    'In eukaryotes, mRNA is transcribed by:',
    ['RNA polymerase II', 'RNA polymerase I', 'RNA polymerase III', 'Reverse transcriptase'],
    [0],
    'Pol II makes mRNA (and snRNA); Pol I makes 28S/18S/5.8S rRNA; Pol III makes tRNA and 5S rRNA.',
    'RNA polymerases'),
  q('mol-4', 'molecular-biology', 'mol-transcription', 'gate', 'mcq', 'medium',
    'The 5′ and 3′ ends of introns removed during splicing are:',
    ['GU and AG', 'AU and CG', 'GU and GA', 'AG and GU'],
    [0],
    'Introns begin with GU and end with AG (the "GT–AG rule"); splicing occurs via two transesterification steps at the branch point.',
    'Splicing'),
  q('mol-5', 'molecular-biology', 'mol-translation', 'gate', 'mcq', 'medium',
    'The peptidyl transferase activity of the ribosome is carried out by:',
    ['23S/28S rRNA (a ribozyme)', 'A ribosomal protein', 'EF-Tu', 'Aminoacyl-tRNA synthetase'],
    [0],
    'Peptide bond formation is catalysed by rRNA — the ribosome is a ribozyme (Nobel: Szostak/Altman work context).',
    'Ribosome catalysis'),
  q('mol-6', 'molecular-biology', 'mol-regulation', 'gate', 'mcq', 'medium',
    'The actual inducer of the lac operon is:',
    ['Allolactose', 'Lactose', 'Glucose', 'IPTG (only in nature)'],
    [0],
    'Lactose is partially converted to allolactose, the true inducer that binds the lac repressor. IPTG is a lab-only inducer.',
    'lac operon'),
  q('mol-7', 'molecular-biology', 'mol-regulation', 'gate', 'mcq', 'medium',
    'CAP (cAMP receptor protein) functions as a:',
    ['Positive regulator (activator) of the lac operon', 'Repressor of the lac operon', 'Structural gene product', 'Terminator'],
    [0],
    'cAMP–CAP binds the promoter and recruits RNA polymerase — positive regulation; the repressor (lacI) is the negative regulator.',
    'lac regulation'),
  q('mol-8', 'molecular-biology', 'mol-ncrna', 'gate', 'mcq', 'medium',
    'CRISPR-Cas9 requires which feature in the target DNA for cutting?',
    ['A PAM sequence (e.g., NGG for SpCas9)', 'A polyA tail', 'A TATA box', 'A telomere'],
    [0],
    'SpCas9 only cuts at sites adjacent to a 5′-NGG-3′ PAM; no PAM, no recognition.',
    'CRISPR requirement'),
  q('mol-9', 'molecular-biology', 'mol-ncrna', 'gate', 'mcq', 'medium',
    'SHERLOCK diagnostics use which Cas protein and target type?',
    ['Cas13 on RNA targets', 'Cas12 on DNA targets', 'Cas9 on DNA targets', 'Cas14 on protein targets'],
    [0],
    'SHERLOCK: Cas13 (RNA target) with collateral cleavage of reporters; DETECTR uses Cas12 on DNA.',
    'CRISPR diagnostics'),
  q('mol-10', 'molecular-biology', 'mol-recombination', 'gate', 'mcq', 'medium',
    'PARP inhibitors (e.g., olaparib) are most effective against tumours with:',
    ['Homologous recombination deficiency (BRCA1/2 loss)', 'High BRCA expression', 'Active mismatch repair', 'No DSBs'],
    [0],
    'Synthetic lethality: HR-deficient cells rely on PARP-mediated repair; blocking PARP is lethal to them, not to normal cells.',
    'Synthetic lethality'),

  // ---------- PLANT BIOTECH ----------
  q('plb-1', 'plant-biotechnology', 'plb-tissue-culture', 'basic', 'mcq', 'easy',
    'In Skoog’s experiments, a HIGH auxin:cytokinin ratio promotes:',
    ['Root formation', 'Shoot formation', 'Callus only', 'Seed formation'],
    [0],
    'High auxin/cytokinin → roots; high cytokinin → shoots; balanced → callus.',
    'Hormone control of differentiation'),
  q('plb-2', 'plant-biotechnology', 'plb-tissue-culture', 'college', 'mcq', 'medium',
    'Virus-free plants are produced by culturing the:',
    ['Apical meristem tip', 'Root tip', 'Xylem', 'Anther'],
    [0],
    'The shoot apical meristem (0.1–0.3 mm) lacks phloem, so viruses (phloem-mobile) are excluded — meristem tip culture.',
    'Virus elimination'),
  q('plb-3', 'plant-biotechnology', 'plb-transformation', 'gate', 'mcq', 'medium',
    'Agrobacterium tumefaciens naturally transfers which DNA into plant cells?',
    ['T-DNA (from the Ti plasmid)', 'The whole Ti plasmid', 'Chloroplast DNA', 'Mitochondrial DNA'],
    [0],
    'Only the T-DNA (bounded by LR/RR) is transferred; vir genes mediate it. Vectors are "disarmed" (oncogenes removed).',
    'Agrobacterium transformation'),
  q('plb-4', 'plant-biotechnology', 'plb-transformation', 'gate', 'mcq', 'medium',
    'Agrobacterium is naturally effective mainly in:',
    ['Woody dicotyledonous plants (at wounds)', 'Graminaceous monocots (rice, wheat)', 'All plants equally', 'Bryophytes only'],
    [0],
    'Agrobacterium’s host range is dicots (especially wounded); monocots generally need the gene gun or adapted Agrob protocols.',
    'Transformation host range'),
  q('plb-5', 'plant-biotechnology', 'plb-crops', 'gate', 'mcq', 'medium',
    'Glyphosate-resistant (Roundup Ready) crops express:',
    ['CP4 EPSPS', 'Bar (phosphinothricin acetyltransferase)', 'Cry1Ac', 'psy + crtI'],
    [0],
    'CP4 EPSPS restores the herbicide-blocked shikimate step; bar confers glufosinate (not glyphosate) resistance.',
    'Herbicide tolerance'),
  q('plb-6', 'plant-biotechnology', 'plb-crops', 'gate', 'mcq', 'medium',
    'Golden Rice addresses which nutritional deficiency?',
    ['Vitamin A (β-carotene)', 'Iron', 'Vitamin C', 'Protein'],
    [0],
    'psy + crtI introduce the carotenoid pathway into rice endosperm → β-carotene (pro-vitamin A).',
    'Biofortification'),
  q('plb-7', 'plant-biotechnology', 'plb-rnai', 'college', 'mcq', 'medium',
    'Co-sense (virus resistance in transgenic plants) works via:',
    ['RNAi silencing of the matching viral genome', 'Production of an antiviral protein', 'Blocking viral entry physically', 'UV inactivation of virus'],
    [0],
    'A viral gene (e.g., coat protein) expressed as a hairpin triggers PTGS that also destroys matching viral RNA — no antiviral protein is made.',
    'Co-sense mechanism'),
  q('plb-8', 'plant-biotechnology', 'plb-editing', 'gate', 'mcq', 'medium',
    'In plants, a CRISPR-Cas9 cut repaired by NHEJ typically results in:',
    ['Small insertions/deletions causing gene knockout', 'Precise base substitution only', 'No change', 'Plasmid integration'],
    [0],
    'NHEJ is error-prone → indels → frameshift knockout; precise edits require HDR with a donor template.',
    'CRISPR editing outcomes'),
  q('plb-9', 'plant-biotechnology', 'plb-genetic-improvement', 'gate', 'mcq', 'medium',
    'SNP markers differ from SSR markers in that SNPs are:',
    ['Biallelic and far more abundant', 'Multiallelic and rare', 'Only dominant', 'Only in mitochondria'],
    [0],
    'SNPs are two-state (biallelic), very dense, cheap and high-throughput; SSRs are multiallelic microsatellites.',
    'Marker types'),
  q('plb-10', 'plant-biotechnology', 'plb-seed', 'gate', 'mcq', 'medium',
    'Recalcitrant seeds (e.g., oak, mango) CANNOT be conserved by:',
    ['Desiccation to low moisture', 'Cryopreservation (−196°C)', 'Ultra-low-temperature storage', 'In-vitro meristem cryo'],
    [0],
    'Recalcitrant seeds die when dried (they must stay moist); only cryo/ULT methods work for them.',
    'Seed conservation'),

  // ---------- PROCESS BIOTECH ----------
  q('pro-1', 'process-biotechnology', 'pro-downstream', 'basic', 'mcq', 'easy',
    'Precipitating proteins by adding high concentrations of ammonium sulfate is called:',
    ['Salting out', 'Salting in', 'Dialysis', 'Diacetate formation'],
    [0],
    'At high salt, ions out-compete proteins for water → solubility drops (salting out); low salt slightly INCREASES solubility (salting in).',
    'Protein precipitation'),
  q('pro-2', 'process-biotechnology', 'pro-purification', 'gate', 'mcq', 'medium',
    'In size-exclusion chromatography, which impurity class is removed by eluting the MONOMER fraction?',
    ['Aggregates', 'DNA', 'Endotoxin', 'Host cell protein'],
    [0],
    'SEC separates by size: aggregates (larger) elute before monomer; collecting the monomer peak removes aggregates.',
    'SEC application'),
  q('pro-3', 'process-biotechnology', 'pro-purification', 'gate', 'mcq', 'medium',
    'Hydrophobic interaction chromatography elutes bound proteins by:',
    ['DECREASING salt concentration', 'Increasing salt concentration', 'Lowering pH to 2', 'Adding imidazole'],
    [0],
    'HIC binds at HIGH salt (hydrophobic patches exposed); elution is by salt DECREASE — the opposite of ion-exchange elution.',
    'HIC elution logic'),
  q('pro-4', 'process-biotechnology', 'pro-quality', 'college', 'mcq', 'medium',
    'The correct sequence of equipment qualification steps is:',
    ['IQ → OQ → PQ', 'PQ → OQ → IQ', 'OQ → IQ → PQ', 'IQ → PQ → OQ'],
    [0],
    'Installation Qualification → Operational Qualification → Performance Qualification (IQ, OQ, PQ).',
    'GMP qualification'),
  q('pro-5', 'process-biotechnology', 'pro-quality', 'gate', 'mcq', 'medium',
    'The standard assay for endotoxin in injectable biopharmaceuticals is the:',
    ['LAL test (limulus amebocyte lysate)', 'Gram stain', 'HPLC', 'ELISA for protein A'],
    [0],
    'The LAL assay detects Gram-negative endotoxin (Lipid A) via the horseshoe crab clotting cascade.',
    'Endotoxin testing'),
  q('pro-6', 'process-biotechnology', 'pro-separation', 'gate', 'mcq', 'medium',
    'The relative volatility α between two components equals 1 means:',
    ['No separation by ordinary distillation is possible', 'Perfect separation in one stage', 'The heavier component is more volatile', 'Total reflux is required'],
    [0],
    'α = 1 means equal volatility (e.g., at an azeotrope) — ordinary distillation cannot separate them.',
    'Distillation feasibility'),
  q('pro-7', 'process-biotechnology', 'pro-economics', 'gate', 'mcq', 'medium',
    'Space-time yield is best defined as:',
    ['Grams of product per litre per hour', 'Grams of product per gram of substrate', 'Conversion percentage', 'Reactor volume'],
    [0],
    'Productivity (space-time yield) = ΔP/(V·t) — it drives reactor sizing and cost.',
    'Process metrics'),
  q('pro-8', 'process-biotechnology', 'pro-separation', 'gate', 'nat', 'medium',
    'A centrifuge runs at 10,000 rpm with a radius of 10 cm. The relative centrifugal force RCF = 1.119×10⁻⁵ × r × n² is approximately (× g):',
    undefined,
    '11190',
    'RCF = 1.119e-5 × 10 × (10000)² = 1.119e-5 × 10 × 1e8 = 1.119e4 ≈ 11,190 × g.',
    'Centrifugation calculation'),
  q('pro-9', 'process-biotechnology', 'pro-cell-therapy', 'gate', 'mcq', 'medium',
    'CAR-T cell therapy products are manufactured from:',
    ['The patient’s own T cells (autologous), typically', 'Bulk animal cells', 'Continuous cell lines only', 'Plant cells'],
    [0],
    'Current CAR-T (Kymriah, Yescarta) is autologous: apheresis → activation → transduction → expansion → infusion over days.',
    'Cell therapy manufacturing'),
  q('pro-10', 'process-biotechnology', 'pro-quality', 'gate', 'msq', 'hard',
    'Which are standard RELEASE tests for a monoclonal antibody? (Select all that apply.)',
    ['Potency (e.g., SPR/cell-based)', 'Aggregation (SE-HPLC/HIC)', 'Sterility', 'pH of the growth medium'],
    [0, 1, 2],
    'Release tests verify identity, potency, purity (aggregates, integrity), sterility and endotoxin. Growth-medium pH is an in-process parameter, not a release test.',
    'Product release'),

  // ---------- RECOMBINANT DNA ----------
  q('rdt-1', 'recombinant-dna', 'rdt-restriction', 'basic', 'mcq', 'easy',
    'EcoRI recognises the sequence GAATTC and produces:',
    ['Sticky (cohesive) 5′ overhangs', 'Blunt ends', 'No cut (it is a methylase)', 'Random nicks'],
    [0],
    'EcoRI cuts G↓AATTC, leaving 5′-AATT overhangs — the classic sticky-end example.',
    'Restriction enzymes'),
  q('rdt-2', 'recombinant-dna', 'rdt-restriction', 'gate', 'mcq', 'medium',
    'Bacteria protect their own DNA from their restriction enzymes by:',
    ['Methylating the recognition sequence', 'Degrading the enzyme', 'Exporting the DNA', 'Increasing chromosome copy number'],
    [0],
    'The restriction–modification system methylates self-DNA at the recognition site, blocking cleavage.',
    'Restriction–modification'),
  q('rdt-3', 'recombinant-dna', 'rdt-vectors', 'college', 'mcq', 'medium',
    'The vector best suited for cloning a 200 kb insert is:',
    ['BAC (Bacterial Artificial Chromosome)', 'Plasmid', 'Cosmid', 'M13 phage'],
    [0],
    'Capacity: plasmid ~1–10 kb, cosmid ~30–45 kb, BAC ~100–300 kb, YAC up to ~2 Mb.',
    'Vector capacity'),
  q('rdt-4', 'recombinant-dna', 'rdt-pcr', 'basic', 'mcq', 'easy',
    'The three steps of each PCR cycle, in order, are:',
    ['Denaturation → annealing → extension', 'Annealing → denaturation → extension', 'Extension → denaturation → annealing', 'Denaturation → extension → annealing'],
    [0],
    'Heat separates strands (94–98°C), primers anneal (~50–65°C), Taq extends (72°C).',
    'PCR cycle'),
  q('rdt-5', 'recombinant-dna', 'rdt-pcr', 'gate', 'nat', 'medium',
    'Starting from 10 copies of a template, how many copies exist after 20 ideal PCR cycles? (Give as 10 × 2^20 ≈ N × 10^6, give N to 1 decimal.)',
    undefined,
    '10.5',
    '10 × 2^20 = 10 × 1,048,576 = 1.0486 × 10^7 ≈ 10.5 × 10^6. So N ≈ 10.5.',
    'PCR amplification math'),
  q('rdt-6', 'recombinant-dna', 'rdt-pcr', 'gate', 'mcq', 'medium',
    'In qPCR, a LOWER CT (cycle threshold) value indicates:',
    ['A HIGHER starting amount of template', 'A lower starting amount', 'A longer amplicon', 'A failed reaction'],
    [0],
    'CT is the cycle at which fluorescence crosses threshold: more template reaches threshold sooner (lower CT).',
    'qPCR interpretation'),
  q('rdt-7', 'recombinant-dna', 'rdt-cloning', 'gate', 'mcq', 'medium',
    'Directional cloning (insert in a fixed orientation, no self-ligation) is achieved by cutting vector and insert with:',
    ['Two different restriction enzymes', 'One restriction enzyme', 'No enzymes (ligation only)', 'DNase I'],
    [0],
    'Two enzymes create non-complementary ends: insert can ligate only one way and vector cannot re-close without insert.',
    'Cloning strategy'),
  q('rdt-8', 'recombinant-dna', 'rdt-sequencing', 'gate', 'mcq', 'medium',
    'Sanger sequencing terminates DNA synthesis because ddNTPs lack:',
    ['A 3′-hydroxyl group', 'A 5′-phosphate', 'A nitrogenous base', 'A sugar'],
    [0],
    'Without the 3′-OH, no new phosphodiester bond can form — chain termination at random positions gives the read.',
    'Sanger chemistry'),
  q('rdt-9', 'recombinant-dna', 'rdt-libraries', 'gate', 'mcq', 'medium',
    'To EXPRESS a eukaryotic gene in E. coli, you should clone:',
    ['cDNA (no introns)', 'Genomic DNA with introns', 'rDNA', 'Any fragment'],
    [0],
    'Bacteria lack spliceosomes — introns would remain; cDNA (from mRNA) is the expressable form.',
    'Library choice'),
  q('rdt-10', 'recombinant-dna', 'rdt-crispr', 'gate', 'mcq', 'medium',
    'Compared with NHEJ, homology-directed repair (HDR) is:',
    ['Precise (donor-template guided) but less efficient', 'More efficient and error-prone', 'Identical in fidelity', 'Only used in viruses'],
    [0],
    'HDR copies a provided donor template (precise edits) but requires homology arms and S/G2 phase, making it less efficient than NHEJ knockouts.',
    'DNA repair outcomes'),

  // ---------- TRANSPORT PROCESSES ----------
  q('trp-1', 'transport-processes', 'trp-momentum', 'basic', 'mcq', 'easy',
    'Flow in a pipe is LAMINAR when the Reynolds number is:',
    ['Less than about 2100', 'Greater than 4000', 'Between 10^6 and 10^7', 'Independent of viscosity'],
    [0],
    'Re < ~2100 laminar; 2100–4000 transitional; > 4000 turbulent.',
    'Flow regimes'),
  q('trp-2', 'transport-processes', 'trp-momentum', 'gate', 'nat', 'medium',
    'Water (ρ = 1000 kg/m³, μ = 0.001 Pa·s) flows at 2 m/s in a 0.05 m pipe. The Reynolds number is:',
    undefined,
    '100000',
    'Re = ρvD/μ = 1000 × 2 × 0.05 / 0.001 = 100,000 → fully turbulent.',
    'Reynolds number'),
  q('trp-3', 'transport-processes', 'trp-momentum', 'college', 'mcq', 'medium',
    'For LAMINAR flow in a circular pipe, pressure drop is proportional to:',
    ['Velocity (ΔP ∝ v)', 'Velocity squared (ΔP ∝ v²)', 'Velocity cubed', 'Flow rate squared'],
    [0],
    'Hagen–Poiseuille: ΔP = 32μvL/D² — linear in v (laminar); turbulent Darcy–Weisbach gives ΔP ∝ v².',
    'Pressure drop regimes'),
  q('trp-4', 'transport-processes', 'trp-heat', 'college', 'mcq', 'medium',
    'The log-mean temperature difference (LMTD) is used to size:',
    ['Heat exchangers with changing temperatures along the exchanger', 'Isothermal heaters only', 'Stirred tanks', 'Pipes with no temperature change'],
    [0],
    'LMTD = (ΔT1 − ΔT2)/ln(ΔT1/ΔT2) accounts for temperature profiles; Q = U·A·LMTD.',
    'Heat exchanger design'),
  q('trp-5', 'transport-processes', 'trp-mass', 'gate', 'mcq', 'medium',
    'In Fenske’s equation, the minimum number of stages at total reflux is found from:',
    ['The relative volatility α and the separation requirement', 'The feed flow rate only', 'The reflux ratio', 'The column diameter'],
    [0],
    'Fenske: Nmin = ln[(xD/(1−xD))((1−xB)/xB)]/ln α — it gives minimum stages (total reflux), not reflux ratio (Underwood does).',
    'Distillation shortcut'),
  q('trp-6', 'transport-processes', 'trp-mass', 'gate', 'mcq', 'medium',
    'The absorption factor A = L/(mG) for good absorption with a finite number of stages should be:',
    ['Greater than 1', 'Less than 0.5', 'Exactly 0', 'Independent of stage count'],
    [0],
    'A > 1 means enough liquid (L) relative to gas (G) and equilibrium slope (m) for high recovery.',
    'Gas absorption'),
  q('trp-7', 'transport-processes', 'trp-control', 'gate', 'mcq', 'medium',
    'A pure proportional controller on a steady process will:',
    ['Leave a steady-state offset (error)', 'Eliminate all error', 'Oscillate indefinitely', 'Drive the process to zero'],
    [0],
    'P-control output is proportional to error, so some residual error is always needed to sustain the output — integral action removes it.',
    'PID behaviour'),
  q('trp-8', 'transport-processes', 'trp-reactors', 'gate', 'mcq', 'medium',
    'For a first-order reaction at the same conversion, the reactor volume requirement is:',
    ['PFR < CSTR', 'PFR > CSTR', 'PFR = CSTR always', 'CSTR = 0'],
    [0],
    'PFR keeps concentration high along its length, so it needs less volume than a CSTR (which operates at outlet conditions) for positive-order kinetics.',
    'Reactor comparison'),
  q('trp-9', 'transport-processes', 'trp-reactors', 'gate', 'mcq', 'medium',
    'The RTD E(t) of an ideal CSTR is:',
    ['Exponential: E(t) = (1/t̄)e^(−t/t̄)', 'A Dirac delta at t̄', 'A Gaussian', 'Uniform on [0, t̄]'],
    [0],
    'Ideal CSTR → exponential residence time distribution; ideal PFR → δ(t − t̄).',
    'Residence time distribution'),
  q('trp-10', 'transport-processes', 'trp-numericals', 'gate', 'nat', 'hard',
    'First-order reaction, X = 0.9, k = 0.5 s⁻¹, v0 = 10 L/s. The CSTR volume V = v0·X/(k(1−X)) in litres is:',
    undefined,
    '180',
    'V = 10 × 0.9 / (0.5 × 0.1) = 9/0.05 = 180 L (PFR would need only ~46 L).',
    'CSTR sizing'),

  // ---------- ENGINEERING MATHEMATICS ----------
  q('emt-1', 'engineering-mathematics', 'emt-linalg', 'basic', 'mcq', 'easy',
    'The determinant of a matrix is ZERO when the matrix is:',
    ['Singular (not invertible)', 'Identity', 'Orthogonal', 'Symmetric'],
    [0],
    'det = 0 ⇔ singular: no unique solution to Ax = b; the matrix cannot be inverted.',
    'Matrix invertibility'),
  q('emt-2', 'engineering-mathematics', 'emt-linalg', 'gate', 'mcq', 'medium',
    'For any square matrix, the sum of eigenvalues equals the:',
    ['Trace', 'Determinant', 'Rank', 'Condition number'],
    [0],
    'tr(A) = Σλ and det(A) = Πλ — two instantly testable identities.',
    'Eigenvalue identities'),
  q('emt-3', 'engineering-mathematics', 'emt-calculus', 'gate', 'mcq', 'medium',
    'For a conservative (gradient) vector field, the line integral around any closed loop is:',
    ['Zero', 'Always positive', 'Equal to the area enclosed', 'Undefined'],
    [0],
    'Conservative fields have zero circulation: ∮∇φ·dr = 0 for every closed path.',
    'Vector calculus'),
  q('emt-4', 'engineering-mathematics', 'emt-ode', 'college', 'mcq', 'medium',
    'The characteristic equation r² + 4r + 13 = 0 has roots that give the homogeneous solution in the form:',
    ['e^(−2t)(C1 cos 3t + C2 sin 3t)', 'C1 e^(13t) + C2 e^(−4t)', 'C1 cos 4t + C2 sin 13t', 't·e^(−4t)'],
    [0],
    'r = (−4 ± √(16−52))/2 = −2 ± 3i → damped oscillation e^(−2t)(C1 cos3t + C2 sin3t).',
    '2nd-order ODEs'),
  q('emt-5', 'engineering-mathematics', 'emt-ode', 'gate', 'mcq', 'medium',
    'The final value theorem in the Laplace domain is valid only when:',
    ['All poles of sF(s) are in the left half-plane (stable system)', 'F(s) has any poles', 'F(s) has no zeros', 'The system is oscillatory'],
    [0],
    'FVT lim t→∞ f(t) = lim s→0 sF(s) requires stability — poles strictly in the LHP.',
    'Laplace theorems'),
  q('emt-6', 'engineering-mathematics', 'emt-prob', 'basic', 'mcq', 'easy',
    'For a Poisson distribution with parameter λ, the mean and variance are both:',
    ['λ', 'λ²', '√λ', '1/λ'],
    [0],
    'Poisson signature: E[X] = Var(X) = λ (e.g., mutations per site).',
    'Probability distributions'),
  q('emt-7', 'engineering-mathematics', 'emt-prob', 'gate', 'mcq', 'medium',
    'A TYPE I error in hypothesis testing is:',
    ['Rejecting a TRUE null hypothesis', 'Failing to reject a false null', 'Increasing sample size', 'Using a one-sided test'],
    [0],
    'Type I (α) = false positive; Type II (β) = false negative (missing a real effect).',
    'Testing errors'),
  q('emt-8', 'engineering-mathematics', 'emt-numerical', 'gate', 'mcq', 'medium',
    'Newton–Raphson iteration has what order of convergence near a simple root?',
    ['Quadratic (2nd order)', 'Linear (1st order)', 'Cubic', 'Superlinear ~1.618'],
    [0],
    'Newton converges quadratically (error squares each step) when f′ ≠ 0 at the root; bisection is linear.',
    'Numerical methods'),
  q('emt-9', 'engineering-mathematics', 'emt-numerical', 'gate', 'mcq', 'medium',
    'Simpson’s 1/3 rule requires the number of sub-intervals to be:',
    ['Even', 'Odd', 'A prime', 'Any integer'],
    [0],
    'The 1/3 rule pairs intervals (weights 4-2-4-2...-4), so it needs an even number of sub-intervals (odd number of points).',
    'Numerical integration'),
  q('emt-10', 'engineering-mathematics', 'emt-transforms', 'gate', 'mcq', 'medium',
    'The Cauchy–Riemann equations for f = u + iv (analyticity) are:',
    ['u_x = v_y and u_y = −v_x', 'u_x = v_x and u_y = v_y', 'u_x = −v_y and u_y = v_x', 'u = v'],
    [0],
    'Analytic ⇔ u_x = v_y, u_y = −v_x (plus differentiability) — the sign pairing is the classic trap.',
    'Complex variables'),

  // ---------- GENERAL APTITUDE ----------
  q('apt-1', 'general-aptitude', 'apt-quant', 'basic', 'mcq', 'easy',
    'A train travels 100 km at 50 km/h and returns 100 km at 100 km/h. The AVERAGE speed for the whole trip is:',
    ['66.7 km/h', '75 km/h', '50 km/h', '100 km/h'],
    [0],
    'Equal distances → harmonic mean: 2×50×100/150 = 66.7 km/h (not the arithmetic mean 75).',
    'Average speed'),
  q('apt-2', 'general-aptitude', 'apt-quant', 'basic', 'mcq', 'easy',
    'A price rises 10% and then falls 10%. The net effect is:',
    ['A 1% decrease', 'No change', 'A 1% increase', 'A 10% decrease'],
    [0],
    '1.10 × 0.90 = 0.99 → net −1% (successive percentages multiply).',
    'Successive percentages'),
  q('apt-3', 'general-aptitude', 'apt-quant', 'college', 'nat', 'medium',
    'A can do a job in 10 days and B in 15 days. Working together, they finish in how many days? (Give 2 d.p.)',
    undefined,
    '6.0',
    'Combined rate = 1/10 + 1/15 = 5/30 = 1/6 → 6.0 days. Answer: 6.0.',
    'Time and work'),
  q('apt-4', 'general-aptitude', 'apt-verbal', 'basic', 'mcq', 'easy',
    'Choose the word closest in meaning to "UBIQUITOUS":',
    ['Pervasive', 'Rare', 'Hostile', 'Transient'],
    [0],
    'Ubiquitous = present everywhere (pervasive, omnipresent).',
    'Vocabulary'),
  q('apt-5', 'general-aptitude', 'apt-verbal', 'college', 'mcq', 'medium',
    'Identify the error: "The committee have agreed to the proposal."',
    ['"have" should be "has" (collective singular)', '"agreed" should be "agree"', 'No error', '"the" should be capitalised'],
    [0],
    'Committee is a collective noun treated as singular here → "has agreed".',
    'Subject–verb agreement'),
  q('apt-6', 'general-aptitude', 'apt-logical', 'gate', 'mcq', 'medium',
    '"If it rains, the ground gets wet. The ground is not wet." The valid conclusion is:',
    ['It did not rain (contrapositive)', 'It rained', 'It may or may not have rained', 'The ground is dry by definition'],
    [0],
    'Contrapositive of P→Q is ¬Q→¬P: not-wet ⇒ not-rain. (The converse would be invalid.)',
    'Logical deduction'),
  q('apt-7', 'general-aptitude', 'apt-logical', 'college', 'mcq', 'medium',
    'All A are B. Some B are C. Which conclusion is VALID?',
    ['No definite relation between A and C can be drawn', 'Some A are C', 'All C are A', 'No A is C'],
    [0],
    '"Some B are C" does not guarantee the C’s include any A — no definite A–C conclusion follows.',
    'Syllogisms'),
  q('apt-8', 'general-aptitude', 'apt-spatial', 'college', 'mcq', 'medium',
    'A man walks 3 km north, then 4 km east. His straight-line distance from the start is:',
    ['5 km', '7 km', '4.5 km', '3.5 km'],
    [0],
    'Perpendicular legs → Pythagoras: √(3² + 4²) = 5 km.',
    'Direction and distance'),
  q('apt-9', 'general-aptitude', 'apt-di', 'gate', 'nat', 'medium',
    'Sales grew from ₹200 L to ₹304.2 L over 3 years. The CAGR = (end/start)^(1/3) − 1 is (%, 1 decimal):',
    undefined,
    '15.0',
    '(304.2/200)^(1/3) − 1 = (1.521)^(1/3) − 1 ≈ 1.15 − 1 = 0.15 → 15.0% (note 1.15³ = 1.5209).',
    'CAGR calculation'),
  q('apt-10', 'general-aptitude', 'apt-reading', 'gate', 'mcq', 'medium',
    'In critical reasoning, an ASSUMPTION of an argument is best described as:',
    ['An unstated premise the argument must take for granted', 'A statement repeated in the passage', 'The conclusion itself', 'A counter-argument'],
    [0],
    'The assumption is the hidden bridge between premises and conclusion — it is NOT stated in the passage.',
    'Critical reasoning'),
];
