import type { Topic } from '../types';

// ============ PLANT BIOTECHNOLOGY ============
export const TOPICS_PLB: Topic[] = [
  {
    id: 'plb-tissue-culture',
    subject: 'plant-biotechnology',
    name: 'Plant Tissue Culture',
    level: 1,
    priority: 'high',
    ord: 1,
    short: 'Growing plants from cells — totipotency in action.',
    basic: {
      what: 'Plant tissue culture grows whole plants from explants (leaf, shoot, embryo) in sterile nutrient medium. It works because plant cells are totipotent — a single cell can regenerate a complete plant.',
      why: 'It underlies micropropagation, transformation and genome editing — the entry point to all plant biotech.',
      how: 'Steps: explant sterilisation (HgCl2/NaOCl + ethanol) → initiation (auxin:cytokinin ratio sets shoot vs root) → proliferation → rooting → acclimatisation (hardening). Media: MS (Murashige–Skoog) base + sucrose + gel + hormones.',
      where: 'Micropropagation (banana, potato), somatic hybrids, transgenic plant production, conservation.',
    },
    college: [
      'Dedifferentiation (callus) → redifferentiation (shoots/roots); plasticity is the key.',
      'Hormone logic: high auxin → root; high cytokinin → shoot; balanced → callus (Skoog experiment).',
      'Totipotency: demonstrated by Steward (1958, carrot suspensor cells → plants).',
      'Somaclonal variation: genetic changes during culture — a problem (uniformity) and opportunity (breeding).',
      'Virus elimination: meristem tip culture (0.1–0.3 mm, apical meristem is virus-free).',
    ],
    advanced: [
      'Protoplast culture: wall removed (cellulase + pectinase) → regeneration; used for somatic hybridisation (PEG fusion, e.g. ‘potato × tomato = pomato’, Carina carrot–tobacco).',
      'Somatic embryogenesis vs organogenesis — two regeneration pathways with different hormone requirements.',
    ],
    gate: {
      highYield: [
        'Auxin:cytokinin ratio → root/shoot/callus (Skoog).',
        'Totipotency + Steward carrot experiment (1958).',
        'Meristem tip culture = virus elimination.',
        'Protoplast = wall-less cell (cellulase + pectinase).',
        'Somaclonal variation definition and consequences.',
      ],
      traps: [
        'High AUXIN → ROOT (not shoot); high cytokinin → shoot — the ratio trap.',
        'Meristem tip is virus-free because viruses move via phloem (vessel-free meristem) — a mechanism question.',
      ],
    },
    examples: [
      'Banana micropropagation: tissue-culture plants are virus-free and uniform.',
      'Carina: carrot × tobacco somatic hybrid (1978) — interspecies fusion.'],
    formulas: [],
    keyPoints: [
      'Totipotent plant cell → whole plant.',
      'Auxin ↑ = root; cytokinin ↑ = shoot; balanced = callus.',
      'Meristem tip = virus-free (phloem-free).',
      'Protoplast = wall removed (enzymes).',
    ],
    revision: {
      remember: 'Auxin-root, cytokinin-shoot; tip culture cures viruses; protoplast = no wall.',
      mistakes: ['Reversing the hormone outcomes.'],
      summary: 'Tissue culture workflow + hormone logic + totipotency + protoplast/somaclonal concepts.',
    },
    related: ['plb-transformation', 'plb-genetic-improvement'],
  },
  {
    id: 'plb-transformation',
    subject: 'plant-biotechnology',
    name: 'Plant Genetic Transformation',
    level: 2,
    priority: 'high',
    ord: 2,
    short: 'Putting genes into plants: Agrobacterium and gene gun.',
    basic: {
      what: 'Plant transformation introduces foreign DNA into plant cells, stable in the genome. Two main methods: Agrobacterium-mediated (natural genetic engineer) and biolistic (gene gun).',
      why: 'Transgenic crops (Bt, herbicide-tolerant, Golden Rice) all start here — a GATE core.',
      how: 'Agrobacterium tumefaciens: Ti plasmid T-DNA transfers to plant genome (vir genes mediate); disarmed (oncogenes removed) vector = safe delivery. Gene gun: gold/tungsten particles coated with DNA shot into cells (bombardment).',
      where: 'Bt cotton, herbicide-tolerant soy, virus-resistant papaya, Golden Rice.',
    },
    college: [
      'Ti plasmid: T-DNA (oncogenes: auxin/cytokinin synthase) + vir region (transfer) + ori + nut genes. Binary vector: small plasmid with T-DNA borders + selectable marker (plant) + vir region on a separate helper plasmid (or same).',
      'Selectable markers: antibiotic (kanamycin/nptII, hygromycin/hpt) or herbicide (bar = phosphinothricin resistance).',
      'Reporters: GUS (GUS staining), GFP (fluorescence), luciferase.',
      'Transformation efficiency: species-dependent (Arabidopsis high via floral dip; cereals low).',
    ],
    advanced: [
      'Floral dip (Agro-dip): dip Arabidopsis flowers in Agrobacterium → transgenic seeds next generation (no tissue culture).',
      'Transgene silencing: methylation of T-DNA; use multiple copies, safe-harbour loci, or gene targeting to stabilise.',
      'CRISPR in plants: Cas9 + sgRNA via Agrobacterium or particle; homoeologous editing in polyploids (wheat).',
    ],
    gate: {
      highYield: [
        'Ti plasmid parts: T-DNA (borders L/R), vir genes, oncogenes (disarmed).',
        'Agrobacterium = natural transformor of WOODY dicots (wounds).',
        'Gene gun = biolistic (no host range limit, but multi-copy random).',
        'Selectable marker examples (nptII-kanamycin, bar-herbicide).',
        'Floral dip = Arabidopsis shortcut.',
      ],
      traps: [
        'Agrobacterium naturally transforms DICOTS (not monocots like rice/wheat) — a host-range trap; monocots need gene gun or improved Agrob.',
        'Oncogenes in Ti plasmid cause CROWN GALL (tumours) — why the vector must be disarmed.',
        'T-DNA borders (LR/RR) are ESSENTIAL for transfer — not the whole plasmid.',
      ],
    },
    examples: [
      'Bt cotton: Cry1Ac (from B. thuringiensis) via Agrobacterium → bollworm resistance.',
      'Golden Rice: psy + crtI (carotenoid pathway) → β-carotene in endosperm.'],
    formulas: [],
    keyPoints: [
      'Agrobacterium: Ti plasmid, T-DNA (disarmed), dicots.',
      'Gene gun: biolistic, any species, random multi-copy.',
      'Markers: nptII (kan), bar (herbicide); reporters: GUS/GFP.',
      'Floral dip = Arabidopsis.',
    ],
    revision: {
      remember: 'Agro=dicots+Ti+T-DNA; gun=any+particles; nptII/bar markers.',
      mistakes: ['Expecting Agrob to work directly on rice.'],
      summary: 'Transformation methods + Ti plasmid logic + markers/reporters + CRISPR-in-plants.',
    },
    related: ['plb-tissue-culture', 'rdt-vectors', 'env-biopesticides'],
  },
  {
    id: 'plb-crops',
    subject: 'plant-biotechnology',
    name: 'Transgenic Crops & GM Food',
    level: 3,
    priority: 'high',
    ord: 3,
    short: 'What GM crops do and the science behind the debate.',
    basic: {
      what: 'Transgenic crops carry engineered traits: pest resistance (Bt), herbicide tolerance (HT), stress tolerance, nutrition (Golden Rice), delayed ripening (Flavr Savr tomato).',
      why: 'GATE covers the traits and the mechanism — not the policy debate, but the biology.',
      how: 'Bt: Cry toxin expressed in plant tissues; insect midgut alkaline pH activates → gut perforation. HT: EPSPS gene (CP4) confers glyphosate resistance; pat (bar) confers glufosinate resistance. Nutrition: carotenoid pathway genes (psy, crtI).',
      where: 'Global agriculture (soy, cotton, maize, canola, sugar beet).',
    },
    college: [
      'Bt crops: Cry1Ac (bollworm), Cry2Ab, Cry1F; stacked traits for resistance management.',
      'HT: CP4-EPSPS (glyphosate) — the most widespread trait globally.',
      'Virus resistance: co-sense (RNAi) — viral coat protein gene silences both transgene and virus (papaya PRSV resistance).',
      'Rice: Golden Rice (pro-vitamin A); iron/zinc biofortification.',
      'Regulation: India — Bt cotton approved (2002); Bt brinjal (eggplant) approved 2017 (commercialisation restricted).',
    ],
    advanced: [
      'Resistance evolution in pests: refuge strategy (non-Bt plants) maintains susceptible population to dilute resistance alleles.',
      'Gene drive crops (sterile insect technique, sterile seed) — containment and spread concerns.',
    ],
    gate: {
      highYield: [
        'Bt mechanism (Cry, alkaline midgut, pore).',
        'CP4-EPSPS = glyphosate resistance.',
        'Co-sense = virus resistance via RNAi (coat protein).',
        'Golden Rice: psy + crtI → β-carotene.',
        'Flavr Savr: first commercial GM (1994, anti-ripening).',
      ],
      traps: [
        'Bt is INSECT-specific (alkaline midgut) — not toxic to humans/mammals (acidic stomach) — a safety-mechanism question.',
        'Co-sense works via RNAi (post-transcriptional silencing), not by making an antiviral protein.',
        'Golden Rice fixes VITAMIN A deficiency (carotene), not iron — a nutrient trap.',
      ],
    },
    examples: [
      'Papain-resistant papaya (Hawai’i): co-sense PRSV coat protein saved the industry.',
      'Bt brinjal (India): Cry1Ac + Cry2Ab for fruit borer.'],
    formulas: [],
    keyPoints: [
      'Bt = Cry + alkaline midgut (insect-specific).',
      'CP4-EPSPS = glyphosate HT.',
      'Co-sense = RNAi virus resistance.',
      'Golden Rice = psy + crtI = β-carotene (vit A).',
      'Flavr Savr = first GM (1994).',
    ],
    revision: {
      remember: 'Cry insects, EPSPS glyphosate, co-sense RNAi, Golden Rice vitamin A.',
      mistakes: ['Calling Bt toxic to mammals; calling co-sense a protein mechanism.'],
      summary: 'GM crop traits + mechanisms + safety logic + landmark crops.',
    },
    related: ['plb-transformation', 'env-biopesticides', 'plb-rnai'],
  },
  {
    id: 'plb-genetic-improvement',
    subject: 'plant-biotechnology',
    name: 'Genetic Improvement: MAS & Conventional Breeding',
    level: 2,
    priority: 'medium',
    ord: 4,
    short: 'From phenotypic selection to marker-assisted and genomic selection.',
    basic: {
      what: 'Genetic improvement = using inheritance to make better crops. Classical: phenotypic selection + hybridisation. Modern: marker-assisted selection (MAS) with DNA markers, and genomic selection (GS) with whole-genome SNPs.',
      why: 'MAS logic (linkage, markers, introgression) is GATE material; connects genetics to agriculture.',
      how: 'MAS: identify marker linked to trait gene → select plants carrying marker (no need to express trait) → introgress into elite background. GS: predict breeding value from all SNP markers (genome-wide) without knowing individual genes.',
      where: 'Disease resistance (blight in potato), quality traits (rice amylose), stress tolerance.',
    },
    college: [
      'Marker types: RFLP, AFLP, SSR (microsatellite), SNP (most abundant, cheap, high-throughput).',
      'Introgression: transfer a trait from a wild donor into an elite cultivar (backcrossing + marker selection to recover donor background).',
      'Heterosis (hybrid vigour): F1 hybrid > both parents (complementation, dominance); used in maize, rice, hybrids.',
      'Genomic selection: training set → predict GEBV → select top 10–20% (no phenotype needed in early generations).',
    ],
    advanced: [
      'Linkage drag: flanking neutral segments co-selected with the target gene; fine mapping + recombinant selection minimises it.',
      'Quantitative trait locus (QTL) mapping: interval mapping, composite interval mapping for polygenic traits.',
    ],
    gate: {
      highYield: [
        'Marker type properties (SNP = abundant/cheap; SSR = codominant, multiallelic; RFLP = dominant).',
        'MAS vs GS: single-gene (MAS) vs polygenic (GS).',
        'Heterosis = F1 > parents.',
        'Introgression + backcrossing logic.',
      ],
      traps: [
        'SNPs are BIALLELIC (not multiallelic like SSR) — a marker-property trap.',
        'MAS needs a KNOWN linked marker for a SPECIFIC trait; GS uses ALL markers for a prediction score.',
      ],
    },
    examples: [
      'Blast resistance in rice via MAS (Pi-ta markers).',
      'Maize hybrid: 90% of US maize is hybrid (heterosis).'],
    formulas: [],
    keyPoints: [
      'SNP = biallelic, abundant, cheap.',
      'MAS = single-trait marker; GS = genome-wide prediction.',
      'Heterosis = F1 vigour.',
      'Backcross + markers = introgression.',
    ],
    revision: {
      remember: 'SNP biallelic; MAS single, GS genome; F1 > parents.',
      mistakes: ['Calling SNPs multiallelic.'],
      summary: 'Breeding evolution: phenotype → MAS (linkage) → GS (genome) with marker properties.',
    },
    related: ['gen-linkage', 'plb-crops', 'plb-transformation'],
  },
  {
    id: 'plb-rnai',
    subject: 'plant-biotechnology',
    name: 'RNAi & Gene Silencing in Plants',
    level: 3,
    priority: 'medium',
    ord: 5,
    short: 'Post-transcriptional gene silencing — a plant superpower.',
    basic: {
      what: 'RNA interference (RNAi) degrades mRNA matching a small RNA (siRNA/miRNA), silencing the gene. In plants, systemic silencing and transgene co-sense make RNAi a powerful tool for pest/virus control.',
      why: 'Virus-resistant papaya and RNAi spray (dicofol-like) are landmark applications; GATE loves the mechanism.',
      how: 'Dicer processes dsRNA → 21–24 nt siRNA → RISC (Argonaute) → mRNA cleavage (PTGS). In transgenics, a hairpin (inverted repeat) makes dsRNA → silences the target gene. Co-sense: viral coat protein transgene triggers silencing of the matching virus.',
      where: 'Virus resistance, gene function studies, insecticidal RNAi sprays (spodoptera).',
    },
    college: [
      'PTGS (post-transcriptional gene silencing): first described in petunia (1990s, Coen, Meyer).',
      'Hairpin (hpRNA) construct: promoter + sense + intron/loop + antisense → dsRNA → robust silencing.',
      'Systemic spread: siRNA moves via phloem (SIRK/HLA proteins) — whole-plant effect.',
      'Applications: virus resistance (coat protein co-sense), insecticidal dsRNA (oral RNAi in lepidoptera), sprayable RNAi.',
    ],
    advanced: [
      'siRNA vs miRNA in plants: siRNA = perfect complement (cleavage); miRNA = often 1 nt mismatch (repression).',
      'Trans-kingdom RNAi: dsRNA sprayed on leaves eaten by insects → gut silencing (spodoptera frugiperda) — regulatory pathway emerging.',
    ],
    gate: {
      highYield: [
        'RNAi pathway: dsRNA → Dicer → siRNA → RISC/Ago → mRNA cleavage.',
        'Co-sense = viral coat protein transgene → virus silencing.',
        'Hairpin construct = inverted repeat → dsRNA.',
        'PTGS = post-transcriptional (mRNA degraded, gene intact).',
      ],
      traps: [
        'RNAi is POST-TRANSCRIPTIONAL — the DNA gene is unchanged (vs transcriptional silencing/methylation).',
        'Co-sense does NOT produce an antiviral protein — it triggers RNAi against the virus.',
      ],
    },
    examples: [
      'Rainbow papaya: cp coat protein transgene → PRSV resistance (1988–1998).',
      'Oral RNAi against fall armyworm (spodoptera) — sprayable dsRNA trials.'],
    formulas: [],
    keyPoints: [
      'dsRNA → Dicer → siRNA → RISC → mRNA cleavage (PTGS).',
      'Co-sense = coat protein → virus RNAi.',
      'Hairpin = inverted repeat dsRNA.',
      'RNAi = post-transcriptional (DNA intact).',
    ],
    revision: {
      remember: 'Dicer-Ago-cleavage; co-sense = coat protein; PTGS = DNA intact.',
      mistakes: ['Calling co-sense a protein mechanism.'],
      summary: 'RNAi machinery + co-sense + hairpin constructs + plant applications.',
    },
    related: ['plb-crops', 'mol-ncrna'],
  },
  {
    id: 'plb-editing',
    subject: 'plant-biotechnology',
    name: 'Genome Editing in Plants (CRISPR)',
    level: 3,
    priority: 'high',
    ord: 6,
    short: 'Precise plant genome editing and the regulatory question.',
    basic: {
      what: 'CRISPR-Cas9 edits plant genomes precisely: guide RNA targets a locus, Cas9 cuts, and the cell repairs (NHEJ → knockout; HDR → knock-in). In plants, it has created drought-tolerant, disease-resistant, and nutritionally improved lines in months, not years.',
      why: 'CRISPR-in-plants is the frontier; GATE asks mechanism + regulatory distinction (mutation breeding vs GMO).',
      how: 'Design sgRNA (20 nt) + PAM (NGG) → deliver (Agrobacterium, particle, or ribonucleoprotein) → DSB → NHEJ (indels, knockout) or HDR (donor template, precise edit). Base editing (C→T, A→G) and prime editing (no DSB) now used in plants.',
      where: 'Soy (high-oleic oil), rice (sub1 submergence), wheat (gliadin for celiac), tomato (non-browning).',
    },
    college: [
      'Off-target effects: guide similarity; mitigation by high-fidelity Cas9 (eSp1.1, HiFi), truncated guides, paired nickase (Cas9n).',
      'Gene stacking and polygenic editing: edit multiple loci (e.g. yield QTLs) in one generation.',
      'Regulatory distinction (debated): no foreign DNA (just a mutation) → many jurisdictions treat as mutation breeding (US, Argentina, Japan); EU treated as GMO until 2018 ruling (now evolving).',
    ],
    advanced: [
      'CRISPRi/a in plants: dCas9-KRAB (silence) or dCas9-VP64 (activate) — reversible, no cut.',
      'Multiplex editing: multiple sgRNAs for multi-locus traits (yield, stress).',
    ],
    gate: {
      highYield: [
        'CRISPR steps: sgRNA + PAM (NGG) + Cas9 → DSB → NHEJ/HDR.',
        'NHEJ = knockout (indels); HDR = knock-in (donor).',
        'Off-target mitigation (high-fidelity Cas9, nickase).',
        'Regulatory logic: no transgene = mutation-like (many jurisdictions).',
      ],
      traps: [
        'CRISPR-edited plant with NO foreign DNA is often regulated as conventional (US) — a "is it GMO?" question depends on the jurisdiction.',
        'Base editors change a BASE without DSB (no cut) — distinct from Cas9 cutting.',
      ],
    },
    examples: [
      'Non-browning mushroom (Crispr Food, 2016): polyphenol oxidase knocked out.',
      'High-oleic soybean: FAD2/FAD3 edited → healthier oil.'],
    formulas: [],
    keyPoints: [
      'sgRNA + PAM (NGG) + Cas9 → DSB.',
      'NHEJ = KO; HDR = KI (donor).',
      'Base/prime editing = no DSB.',
      'No-transgene edit ≈ mutation (US/JP/AR regulatory view).',
    ],
    revision: {
      remember: 'PAM NGG; NHEJ KO, HDR KI; base editor no cut; no transgene = mutation-like.',
      mistakes: ['Calling base editing a DSB method.'],
      summary: 'Plant CRISPR: mechanism + repair outcomes + off-target + regulatory distinction.',
    },
    related: ['plb-transformation', 'mol-ncrna', 'rdt-crispr'],
  },
  {
    id: 'plb-seed',
    subject: 'plant-biotechnology',
    name: 'Seed Biotechnology & Storage',
    level: 3,
    priority: 'low',
    ord: 7,
    short: 'Seed science: priming, coating, and gene banks.',
    basic: {
      what: 'Seed biotech improves germination, vigour and storage: seed priming (controlled water stress), coating (nutrients/pesticides/microbes), and long-term conservation in gene banks (Svalbard vault).',
      why: 'Connects plant biotech to food security and conservation; GATE touches storage and priming.',
      how: 'Priming: soak seeds partially → dry → faster, uniform germination (metabolic prep without growth). Coating: polymer + bio/chemicals on seed surface. Storage: desiccation (2–8°C, 15–30% moisture) for orthodox seeds; recalcitrant seeds (oak, mango) need cryo (−196°C) or ultra-low temp.',
      where: 'Agriculture, climate-resilient seed supply, conservation (Svalbard).',
    },
    college: [
      'Orthodox vs recalcitrant seeds: orthodox desiccate well (most crops); recalcitrant die if dried (tropical tree species).',
      'Seed priming mechanism: water uptake → metabolic activation → oxidative stress → repair (ABR, ABA, H2O2 signalling) → dry → germination boost.',
      'Biocoating: rhizobium/PSB (phosphate solubilising bacteria) on legume/cereal seeds for biofertilisation.',
      'Svalbard vault: ~1 million accessions, −18°C, permanent backup for global gene banks.',
    ],
    advanced: [
      'Recalcitrant seed conservation: vitrification (cryoprotectants + rapid cooling) or in-vitro meristem cryo.',
      'Seed vigour assays: radicle length, electrolyte leakage, tetrazolium (vitality) test.',
    ],
    gate: {
      highYield: [
        'Orthodox (desiccation-tolerant) vs recalcitrant (sensitive).',
        'Priming = partial imbibition → uniform germination.',
        'Biocoating = seed-delivered microbes/chemicals.',
        'Svalbard = global backup vault.',
      ],
      traps: [
        'Recalcitrant seeds CANNOT be stored dry — they die (opposite of orthodox) — a storage trap.',
        'Priming does NOT grow the seed — it primes metabolism (no radicle emergence).',
      ],
    },
    examples: [
      'Svalbard: potato diversity (including wild Solanum) preserved against climate loss.',
      'PSB-coated rice seed → phosphate uptake boost in low-P soils.'],
    formulas: [],
    keyPoints: [
      'Orthodox = dry-storable; recalcitrant = cryo only.',
      'Priming = partial imbibition, no growth.',
      'Biocoating = seed-delivered inoculants.',
    ],
    revision: {
      remember: 'Orthodox dry, recalcitrant cryo; priming = no growth; Svalbard = backup.',
      mistakes: ['Storing recalcitrant seeds dry.'],
      summary: 'Seed types + priming + coating + conservation logistics.',
    },
    related: ['plb-tissue-culture', 'env-biodiversity'],
  },
  {
    id: 'plb-gate',
    subject: 'plant-biotechnology',
    name: 'GATE Focus: Plant Biotech',
    level: 4,
    priority: 'high',
    ord: 8,
    short: 'Hormone ratios, transformation hosts and GM mechanisms.',
    basic: {
      what: 'GATE plant biotech = hormone ratio logic + transformation host range + GM crop mechanism banks + RNAi/CRISPR precision.',
      why: 'High recall yield with a few recurring traps.',
      how: 'Drill: auxin/cytokinin outcomes, Agrob host range, Bt/EPSPS/co-sense mechanisms, Golden Rice genes, CRISPR repair outcomes.',
      where: 'GATE BT paper.',
    },
    college: [
      'Hormone bank: auxin ↑ = root, cytokinin ↑ = shoot, balanced = callus.',
      'Transformation: Agrob = dicots (Ti, T-DNA, disarmed); gene gun = monocots + any.',
      'GM bank: Bt = Cry (insect), EPSPS = glyphosate, co-sense = virus (RNAi), Golden Rice = psy+crtI (vit A), Flavr Savr = anti-ripening (1994).',
      'RNAi: Dicer → siRNA → RISC → PTGS; co-sense = coat protein.',
    ],
    advanced: [
      'Multi-step: "dicot pest-resistance via natural pathogen" → Agrob-Ti-Cry.',
      'Regulatory: no-transgene CRISPR = mutation-like (US view).',
    ],
    gate: {
      highYield: [
        'Hormone ratios + host range + GM mechanism bank + RNAi/CRISPR.',
      ],
      traps: [
        'Agrob on rice (monocot) = the trap (needs gene gun or improvement).',
        'Bt mammal toxicity = false (acidic stomach).',
        'Co-sense = RNAi, not protein.',
      ],
    },
    examples: [
      '"High cytokinin in culture medium produces..." → shoots.',
      '"Virus-resistant papaya mechanism" → co-sense RNAi (coat protein).'],
    formulas: [],
    keyPoints: [
      'Auxin-root, cytokinin-shoot, balanced-callus.',
      'Agro=dicots, gun=any.',
      'GM mechanism bank (Bt/EPSPS/co-sense/Golden Rice).',
      'RNAi = PTGS; CRISPR = NHEJ/HDR.',
    ],
    revision: {
      remember: 'Hormone outcomes + host range + GM bank + RNAi/CRISPR precision.',
      mistakes: ['Host-range and mechanism swaps.'],
      summary: 'Plant biotech GATE = hormone logic + host range + GM/RNAi/CRISPR banks.',
    },
    related: ['plb-tissue-culture', 'plb-transformation', 'plb-crops'],
  },
];

// ============ PROCESS BIOTECHNOLOGY ============
export const TOPICS_PRO: Topic[] = [
  {
    id: 'pro-downstream',
    subject: 'process-biotechnology',
    name: 'Downstream Processing Overview',
    level: 1,
    priority: 'high',
    ord: 1,
    short: 'From broth to product: the recovery pipeline.',
    basic: {
      what: 'Downstream processing (DSP) recovers and purifies the product from fermentation broth: cell removal → product isolation → purification → formulation. It is often 50–80% of total process cost for proteins.',
      why: 'DSP cost and unit-operation selection are core GATE process biotech.',
      how: 'Primary recovery: filtration/centrifugation (remove cells) → extraction (cell disruption if intracellular, or direct if secreted) → precipitation. Purification: chromatography (affinity, IEX, SEC, RP-HPLC). Formulation: concentration, buffer exchange, drying (lyophilisation).',
      where: 'Antibodies, enzymes, vitamins, metabolites, cell therapy.',
    },
    college: [
      'Cell disruption (intracellular products): homogenisation, bead-beating, sonication, enzymatic (lysozyme), osmotic shock.',
      'Precipitation: ammonium sulfate (salting out — TSI), organic solvent (cold, denaturation risk), isoelectric (pH = pI).',
      'Purification metrics: purity (mg product/mg total protein), yield (% product recovered), purification fold, specific activity.',
      'Formulation: stabilisers (sucrose, trehalose, polysorbate), pH 5–6, 2–8°C or lyophilised.',
    ],
    advanced: [
      'Continuous DSP: tangential flow filtration (TFF) and capture chromatography in continuous mode (reduces footprint).',
      'Process analytical technology (PAT): in-process monitoring (UV, IR, Raman) for quality-by-design.',
    ],
    gate: {
      highYield: [
        'DSP sequence: removal → isolation → purification → formulation.',
        'Ammonium sulfate = salting out (TSI, non-specific).',
        'Purification fold = specific activity ratio.',
        'Cell disruption methods for intracellular products.',
        'Lyophilisation = freeze-drying (heat-sensitive).',
      ],
      traps: [
        'Salting out (ammonium sulfate) PRECIPITATES proteins (reduces solubility); "salting in" is at low salt (increases solubility) — a direction trap.',
        'Affinity chromatography is high-specificity (first step for tagged proteins); SEC separates by SIZE (not charge).',
      ],
    },
    examples: [
      'mAb DSP: harvest → clarification (depth filter) → Protein A capture → AEX polish → viral inactivation (pH 4, 24 h) → TFF formulation → fill-finish.',
      'Insulin (E. coli): cell lysis → inclusion body solubilisation → refolding → ion exchange → RP-HPLC.'],
    formulas: [
      { name: 'Purification fold', expr: 'PF = (SA_final / SA_initial)' },
      { name: 'Yield', expr: 'Y% = (total activity_final / total activity_initial) × 100' },
    ],
    keyPoints: [
      'DSP = removal → isolation → purification → formulation.',
      'Salting out = ammonium sulfate (↓ solubility).',
      'PF = SA ratio; yield = activity ratio.',
      'Lyophilisation for heat-labile.',
    ],
    revision: {
      remember: 'Remove-isolate-purify-formulate; salt-out = (NH4)2SO4; PF = SA ratio.',
      mistakes: ['Swapping salting in/out.'],
      summary: 'DSP pipeline + precipitation + purification metrics + formulation logic.',
    },
    related: ['ins-chromo', 'pro-purification', 'mib-bioprocessing'],
  },
  {
    id: 'pro-purification',
    subject: 'process-biotechnology',
    name: 'Protein Purification Techniques',
    level: 2,
    priority: 'high',
    ord: 2,
    short: 'Chromatography and separation for proteins.',
    basic: {
      what: 'Protein purification uses differential properties: charge (ion exchange), size (SEC), hydrophobicity (HIC, RP-HPLC), affinity (specific binding), and isoelectric point (IEF, isoelectric precipitation).',
      why: 'Chromatography selection and elution logic are GATE favourites.',
      how: 'Typical mAb flow: Protein A (affinity) → AEX (anion exchange, salt gradient) → SEC (aggregates) → virucide → formulation. Each step removes a class of impurity (HCP, aggregates, aggregates, DNA, endotoxin).',
      where: 'Therapeutic proteins, enzymes, diagnostics.',
    },
    college: [
      'Affinity: ligand-specific (Protein A–Fc, His–Ni, lectin–glycan); highest specificity, first step for tagged proteins.',
      'Ion exchange: CEX (binds negative at low pH), AEX (binds positive at high pH); elute by salt or pH shift.',
      'Size exclusion: large elute FIRST (excluded); separates aggregates from monomer; also buffer exchange.',
      'Hydrophobic interaction (HIC): high salt binds hydrophobic; elute by salt DECREASE.',
      'RP-HPLC: C18, organic gradient; polypeptide analysis (integrity).',
      'Isoelectric focusing: separate by pI in pH gradient.',
    ],
    advanced: [
      'Viral clearance: nanofiltration (20 nm), low-pH hold (pH 4, 24 h), CEX/IEX viral removal, solvent/detergent (S/D) — a multi-barrier strategy.',
      'Endotoxin removal: anion exchange (endotoxin is negatively charged), chromatographic polishing.',
    ],
    gate: {
      highYield: [
        'Mode → separation principle → elution logic table.',
        'SEC: large first; RP-HPLC: hydrophobic last; HIC: salt decrease elutes.',
        'Affinity first for tagged proteins (His-Ni, Protein A).',
        'Viral clearance multi-barrier (NF + pH + CEX).',
      ],
      traps: [
        'HIC elutes by SALT DECREASE (opposite of IEX which elutes by salt increase) — a direction trap.',
        'CEX binds NEGATIVE proteins (at pH below their pI); AEX binds POSITIVE.',
        'SEC does NOT purify by charge or affinity — size only.',
      ],
    },
    examples: [
      'His-tagged protein: Ni-NTA affinity (imidazole elution) → DEAE → SEC.',
      'mAb viral safety: low-pH (pH 4) + nanofiltration + CEX = 3-log virus reduction per step.'],
    formulas: [],
    keyPoints: [
      'Affinity (specific) → IEX (charge) → SEC (size) → HIC/RP (hydrophobic).',
      'SEC large first; HIC salt-decrease; IEX salt-increase.',
      'CEX = negative; AEX = positive.',
      'Viral clearance = multi-barrier.',
    ],
    revision: {
      remember: 'SEC big-first; HIC salt-down; IEX salt-up; affinity first.',
      mistakes: ['HIC/IEX elution direction swaps.'],
      summary: 'Purification mode table + elution logic + viral/endotoxin clearance.',
    },
    related: ['ins-chromo', 'pro-downstream'],
  },
  {
    id: 'pro-economics',
    subject: 'process-biotechnology',
    name: 'Fermentation Economics & Scale',
    level: 3,
    priority: 'medium',
    ord: 3,
    short: 'Cost drivers, productivity and the business of scale.',
    basic: {
      what: 'Bioprocess economics: cost of goods = substrate + energy + labour + downstream + capital amortisation. Productivity (g/L/h) and yield (g/g) drive the economics; scale affects all.',
      why: 'GATE asks cost drivers and the productivity-yield trade-off; links to Bioreaction.',
      how: 'High productivity → smaller/fewer reactors. High yield → less substrate. Downstream often dominates (50–80%) for secreted proteins. Scale-up must preserve kLa, mixing, shear (Bioreaction).',
      where: 'Process development, tech transfer, plant design.',
    },
    college: [
      'Capital vs operating cost: large plants have high capital but low unit cost (economies of scale).',
      'Cost breakdown (typical biotech): substrate 30–50%, downstream 30–60% (proteins), energy 10–20%.',
      'Cell density limits: O2, nutrients, waste (ammonia, acids), shear, heat removal.',
      'Space-time yield = productivity; the key comparison between reactor types.',
    ],
    advanced: [
      'Quality by Design (QbD): define Critical Quality Attributes (CQAs) → Critical Process Parameters (CPPs) → control strategy (design space).',
      'Continuous manufacturing: perfusion + continuous DSP → smaller footprint, tighter control.',
    ],
    gate: {
      highYield: [
        'Cost driver ranking (downstream for proteins).',
        'Titer / yield / productivity definitions.',
        'Scale-up parameters (kLa, P/V, shear).',
        'QbD: CQA → CPP → design space.',
      ],
      traps: [
        'High yield + low productivity can be uneconomic (long batch) — a logic trap.',
        'Contamination in continuous = total batch loss (vs batch recovery).',
      ],
    },
    examples: [
      'Antibody: 5–10 g/L, 30-day batch, downstream ~70% of COGS.',
      'Citric acid: cheap substrate + high titer = low COGS despite commodity product.'],
    formulas: [
      { name: 'Space-time yield', expr: 'STY = P/t (g/L/h)' },
    ],
    keyPoints: [
      'Titer (g/L), yield (g/g), productivity (g/L/h).',
      'Downstream dominates for proteins.',
      'Scale-up preserves kLa/P/V/shear.',
      'QbD = CQA → CPP → design space.',
    ],
    revision: {
      remember: 'Titer/yield/productivity; downstream = cost king; QbD chain.',
      mistakes: ['Optimising yield while ignoring batch time.'],
      summary: 'Bioprocess economics: big three + cost drivers + scale-up + QbD.',
    },
    related: ['mib-bioprocessing', 'bae-scaleup', 'pro-downstream'],
  },
  {
    id: 'pro-quality',
    subject: 'process-biotechnology',
    name: 'Quality Control, Validation & GMP',
    level: 3,
    priority: 'medium',
    ord: 4,
    short: 'Making biotech products safe and consistent.',
    basic: {
      what: 'Quality control (QC) tests the product; quality assurance (QA) builds the system. GMP (Good Manufacturing Practice) is the regulatory framework: documented, validated, controlled processes that consistently produce safe, effective product.',
      why: 'Regulatory logic (validation, in-process controls, release testing) is GATE material.',
      how: 'In-process controls (IPC): at-line tests during manufacturing (pH, DO, titer, sterility). Validation: process validation (prospective/concurrent), equipment (IQ/OQ/PQ), analytical method validation. Release: potency, purity, identity, sterility, endotoxin, viral safety.',
      where: 'Therapeutic proteins, vaccines, cell/gene therapy.',
    },
    college: [
      'Analytical methods for proteins: SDS-PAGE (size), CE-SDS (integrity), HIC (aggregates), RP-HPLC (peptide map), SPR (binding), cell-based potency.',
      'Impurity classes: HCP (host cell protein), DNA, protein aggregates, misfolded, host cell metabolites, endotoxin, viruses, particles.',
      'ICH Q8 (QbD), Q9 (risk management, FMEA), Q10 (pharma quality system), Q11 (development).',
      'Sterility testing: membrane filtration, 14-day incubation (bacterial + fungal).',
    ],
    advanced: [
      'Risk management: FMEA (failure mode and effects) scores RPN = S × O × D; prioritises controls.',
      'Continuous verification and process capability (Cpk) in commercial operations.',
    ],
    gate: {
      highYield: [
        'IQ/OQ/PQ (installation/operational/qualification).',
        'Impurity classes for biotech products.',
        'Release tests: potency, purity, identity, sterility, endotoxin.',
        'FMEA: RPN = S × O × D.',
        'ICH Q8/Q9/Q10 scope.',
      ],
      traps: [
        'IQ/OQ/PQ order: Install → Operate → Perform (Qualify) — a sequence trap.',
        'Endotoxin test = LAL (limulus amebocyte lysate), not sterility — different assays.',
        'Sterility test takes 14 days — not a real-time release test (it’s a hold-point).',
      ],
    },
    examples: [
      'mAb release: SE-HPLC (aggregates), CE-SDS (integrity), SPR (potency), LAL (endotoxin), sterility (14 d).',
      'FMEA: a filling machine leak (S=9, O=3, D=2) → RPN=54 → add in-line particle counter (D drops to 1 → RPN=27).'],
    formulas: [
      { name: 'RPN (FMEA)', expr: 'RPN = Severity × Occurrence × Detection' },
    ],
    keyPoints: [
      'IQ → OQ → PQ (qualification sequence).',
      'Impurities: HCP, DNA, aggregates, endotoxin, virus.',
      'Release: potency/purity/identity/sterility/endotoxin.',
      'RPN = S×O×D; LAL = endotoxin.',
    ],
    revision: {
      remember: 'IQ-OQ-PQ; impurity classes; RPN=SOD; LAL=endotoxin.',
      mistakes: ['Ordering PQ before OQ.'],
      summary: 'GMP logic: validation + QC/QA + impurity/release tests + FMEA.',
    },
    related: ['pro-downstream', 'pro-economics'],
  },
  {
    id: 'pro-cell-therapy',
    subject: 'process-biotechnology',
    name: 'Cell & Gene Therapy Manufacturing',
    level: 3,
    priority: 'low',
    ord: 5,
    short: 'Living products: the hardest manufacturing problem.',
    basic: {
      what: 'Cell and gene therapies are LIVING products: CAR-T cells, stem cell grafts, viral vectors, CRISPR-edited cells. Manufacturing must keep cells alive, functional, and safe — far harder than purified proteins.',
      why: 'The frontier of biotech manufacturing; GATE touches the unique challenges.',
      how: 'CAR-T: apheresis → T-cell activation (CD3/CD28) → transduction (lentiviral/viral vector with CAR) → expansion → wash/formulate → infuse (days, not months). Viral vectors: producer cell lines (HEK293), harvest → clarification → ultracentrifugation or chromatography → formulation → fill.',
      where: 'Oncology (CAR-T: Kymriah, Yescarta), haemoglobinopathies (CRISPR: Casgevy), monogenic disease.',
    },
    college: [
      'Vector production: AAV (HEK293, empty/full particle separation), lentivirus (producers, retroviral safety), adenovirus (high titre).',
      'Cell therapy QC: viability (>70–80%), identity (flow), potency (functional assay), sterility, mycoplasma, residual vector, off-target (gene editing).',
      'Regulatory: personalised (autologous) vs off-the-shelf (allogeneic); batch records per patient.',
    ],
    advanced: [
      'Allogeneic CAR-T: HLA-matched or CRISPR-edited (HLA knockout) to avoid GvHD; manufacturing standardisation.',
      'In-vivo CAR-T and base-edited therapies (next generation) — manufacturing shifts to delivery, not cell processing.',
    ],
    gate: {
      highYield: [
        'CAR-T workflow (apheresis → activate → transduce → expand → infuse).',
        'AAV empty/full separation (cesium gradient or chromatography).',
        'Cell therapy QC: viability, potency, identity, sterility, residual vector.',
        'Autologous (personalised) vs allogeneic (off-the-shelf).',
      ],
      traps: [
        'CAR-T is made from the PATIENT’S OWN cells (autologous) — not a mass-produced product — a manufacturing-logic question.',
        'AAV "empty" capsids (no genome) are an impurity, not active product — must be separated.',
      ],
    },
    examples: [
      'Kymriah (tisagenlecleucel): first CAR-T (2017, B-ALL).',
      'Casgevy (exagamglogene autotemcel): CRISPR-edited autologous CD34+ for sickle cell (2023).'],
    formulas: [],
    keyPoints: [
      'CAR-T: patient cells, personalised, days-scale.',
      'AAV: empty/full separation.',
      'QC: viability/potency/identity/sterility/residual vector.',
      'Autologous vs allogeneic.',
    ],
    revision: {
      remember: 'CAR-T = patient cells; AAV empty/full; QC = viability+potency+identity.',
      mistakes: ['Treating CAR-T as a batch product.'],
      summary: 'Living-product manufacturing: CAR-T + vectors + QC + regulatory logic.',
    },
    related: ['an-mab', 'mol-ncrna', 'pro-quality'],
  },
  {
    id: 'pro-separation',
    subject: 'process-biotechnology',
    name: 'Separation & Concentration Operations',
    level: 2,
    priority: 'medium',
    ord: 6,
    short: 'Filtration, centrifugation, membrane and drying.',
    basic: {
      what: 'Separation operations remove or concentrate material: filtration (depth, membrane), centrifugation (differential, continuous), membranes (ultrafiltration, nanofiltration, reverse osmosis), evaporation, crystallisation, drying.',
      why: 'Unit operation selection + operating logic are GATE process questions.',
      how: 'Depth filtration: trapped in a mat (clarification). Membrane: by size (UF 1–100 nm proteins; NF 0.1–1 nm salts/monovalent; RO <0.1 nm water). Centrifugation: RCF = 1.119 × 10^−5 × r × n² (g). Drying: spray (fast, heat-sensitive), freeze (lyophilisation, most stable).',
      where: 'Broth clarification, concentration, viral removal, final drying.',
    },
    college: [
      'Membrane cascade: MF (0.1–0.2 µm, cells/bacteria) → UF (concentrate protein) → NF (desalt, virus) → RO (water).',
      'Tangential flow filtration (TFF/Cross-flow): reduces fouling vs dead-end; concentration factor (CF) = retentate volume ratio.',
      'Centrifugation: RCF (relative centrifugal force); pelleting vs partitioning.',
      'Crystallisation: controlled supersaturation (protein crystals for X-ray; small-molecule APIs).',
      'Drying: spray (milk, enzymes), freeze (vaccines, mAbs), fluidised bed.',
    ],
    advanced: [
      'Viral removal by nanofiltration: 20 nm pore → >4-log reduction for viruses >30 nm.',
      'Diafiltration: buffer exchange + desalting (DV = dialysate volume / feed volume).',
    ],
    gate: {
      highYield: [
        'Membrane size ladder: MF → UF → NF → RO.',
        'RCF formula and what it means.',
        'TFF vs dead-end (fouling).',
        'Drying method → product stability (lyo = best for proteins).',
        'Nanofiltration viral removal (20 nm).',
      ],
      traps: [
        'UF removes PROTEINS (retains them, passes buffer); "ultrafiltration concentrates protein" — direction of retention matters.',
        'RCF depends on r AND n² (not just n) — a units trap.',
        'Spray drying is FAST but heat-exposed; lyophilisation is slow but preserves activity.',
      ],
    },
    examples: [
      'mAb concentration: UF/DF at 4°C, diafiltration into formulation buffer (5–10 DV).',
      'Vaccine: lyophilised with trehalose stabiliser → shelf-stable at 2–8°C.'],
    formulas: [
      { name: 'RCF', expr: 'RCF = 1.119 × 10⁻⁵ × r(cm) × n(rpm)²' },
    ],
    keyPoints: [
      'MF→UF→NF→RO size ladder.',
      'TFF = cross-flow (less fouling).',
      'RCF = 1.119e-5 × r × n².',
      'Lyo = most stable for proteins.',
    ],
    revision: {
      remember: 'MF/UF/NF/RO; RCF = r·n²; lyo = stable.',
      mistakes: ['UF direction (retains protein).'],
      summary: 'Separation operations: membrane ladder + centrifugation + TFF + drying logic.',
    },
    related: ['pro-downstream', 'ins-chromo'],
  },
  {
    id: 'pro-bioprocess',
    subject: 'process-biotechnology',
    name: 'Bioprocess Design & Intensification',
    level: 3,
    priority: 'low',
    ord: 7,
    short: 'Designing efficient, modern bioprocesses.',
    basic: {
      what: 'Bioprocess design integrates upstream (fermentation) and downstream (DSP) into an efficient, controllable, scalable system. Intensification makes it faster, smaller, and greener.',
      why: 'Connects all process concepts; GATE asks design logic and trade-offs.',
      how: 'Design: define CQA → choose host/strain → fermentation (batch/fed-batch/perfusion) → DSP (capture → qualify → finish) → formulation. Intensification: continuous processes, single-use bioreactors (USBR), in-line analytics, smaller-footprint.',
      where: 'Biopharma, biofuels, industrial enzymes.',
    },
    college: [
      'Single-use systems (USBR, tubing bags): reduce cleaning/CIP cost, faster changeover; trade-offs: cost per run, waste, scale limits.',
      'Continuous bioprocessing: perfusion + continuous chromatography → 24/7 production, tighter control, smaller footprint.',
      'PAT: in-line sensors (UV, pH, DO, Raman) + multivariate analysis for real-time quality.',
      'Process design space (ICH Q8): validated operating ranges → flexibility within space.',
    ],
    advanced: [
      'Digital twins: model-based simulation of bioreactors for scale-up and control (CFD + kinetic models).',
      'Green bioprocessing: water/energy reduction, renewable feedstocks, waste minimisation.',
    ],
    gate: {
      highYield: [
        'USBR pros (speed, no CIP) vs cons (cost, scale).',
        'Continuous = perfusion + continuous DSP.',
        'PAT = in-line + real-time quality.',
        'Design space = validated operating range.',
      ],
      traps: [
        'USBR reduces cleaning cost but INCREASES per-run consumable cost — a trade-off question.',
        'Perfusion requires CELL RETENTION (TFF) — not just continuous feed.',
      ],
    },
    examples: [
      'Single-use 2000 L USBR for a mAb campaign: 3 weeks setup vs 3 months (CIP/SIP) for stainless.',
      'Continuous AAV process: perfusion + continuous chromatography → 10× smaller footprint.'],
    formulas: [],
    keyPoints: [
      'USBR: fast + no CIP; cost + scale trade-offs.',
      'Continuous = perfusion + retention + continuous DSP.',
      'PAT = in-line real-time quality.',
      'Design space = validated range.',
    ],
    revision: {
      remember: 'USBR trade-offs; continuous = retention; PAT = in-line.',
      mistakes: ['Perfusion without cell retention.'],
      summary: 'Modern bioprocess design: USBR + continuous + PAT + design space.',
    },
    related: ['bae-fedbatch', 'pro-quality', 'pro-economics'],
  },
  {
    id: 'pro-gate',
    subject: 'process-biotechnology',
    name: 'GATE Focus: Process Biotech',
    level: 4,
    priority: 'high',
    ord: 8,
    short: 'Purification logic, metrics and unit operations.',
    basic: {
      what: 'GATE process biotech = purification mode table + DSP sequence + cost metrics + unit operation logic + GMP sequence.',
      why: 'High recall yield with direction traps (elution, membrane retention).',
      how: 'Drill: mode→principle→elution, titer/yield/productivity, IQ/OQ/PQ, MF/UF/NF/RO, RCF.',
      where: 'GATE BT paper.',
    },
    college: [
      'Purification table: affinity (specific, first), IEX (charge; CEX neg/AEX pos), SEC (size; big first), HIC (hydrophobic; salt down), RP (organic).',
      'Metrics: PF = SA ratio; yield = activity ratio; STY = P/t.',
      'GMP: IQ→OQ→PQ; RPN = S×O×D; LAL = endotoxin.',
      'Unit ops: MF/UF/NF/RO; RCF = r·n²; lyo = stable.',
    ],
    advanced: [
      'Multi-step: "purify a His-tagged cytosolic protein" → Ni-NTA → DEAE → SEC.',
      'Cost logic: downstream dominates for proteins.',
    ],
    gate: {
      highYield: [
        'Purification + metrics + GMP + unit op banks.',
      ],
      traps: [
        'HIC elution (salt down) vs IEX (salt up).',
        'SEC big-first; UF retains protein.',
        'IQ/OQ/PQ order.',
      ],
    },
    examples: [
      '"First step for a His-tagged protein" → Ni-NTA affinity.',
      '"Largest molecule elutes first in..." → SEC.'],
    formulas: [],
    keyPoints: [
      'Purification table + elution directions.',
      'PF/yield/STY.',
      'IQ→OQ→PQ; RPN; LAL.',
      'Membrane ladder + RCF.',
    ],
    revision: {
      remember: 'Mode table + metrics + GMP order + membrane ladder.',
      mistakes: ['Elution direction swaps.'],
      summary: 'Process GATE = purification logic + metrics + GMP + unit ops, drilled to speed.',
    },
    related: ['pro-downstream', 'pro-purification', 'pro-quality'],
  },
];

// ============ RECOMBINANT DNA TECHNOLOGY ============
export const TOPICS_RDT: Topic[] = [
  {
    id: 'rdt-restriction',
    subject: 'recombinant-dna',
    name: 'Restriction Enzymes & DNA Cutting',
    level: 1,
    priority: 'high',
    ord: 1,
    short: 'Molecular scissors: types and sticky/blunt ends.',
    basic: {
      what: 'Restriction enzymes (restriction endonucleases) cut DNA at specific recognition sequences. Type II (the lab workhorse) cuts at or near a palindromic sequence, producing sticky (cohesive) or blunt ends.',
      why: 'Restriction mapping and cloning logic are GATE staples; the enzymes are the foundation of all recombinant DNA work.',
      how: 'Type I (cut far from site, need ATP), Type II (site-specific, lab use), Type III (cut ~26 bp away). Sticky ends (EcoRI: G↓AATTC → 5′ overhang) anneal complementarily → ligated easily. Blunt ends (SmaI: CCC↓GGG) ligated less efficiently.',
      where: 'Cloning, mapping, RFLP, forensic DNA, CRISPR (adaptation).',
    },
    college: [
      'Naming: organism-genus-strain-number (EcoRI = Escherichia coli RY13, first).',
      'Isoschizomers: different enzymes, same recognition site (e.g. HpaII / MspI, both CCGG). Neoschizomers: related enzymes, distinct recognition sites (e.g. HpaII CCGG vs HpyCH4IV CCGG).',
      'Methylation: host methylates its own recognition site → self-DNA protection (restriction–modification system = bacterial immunity).',
      'RFLP: restriction + Southern blot for genotype (VNTR); forensic paternity, disease (sickle cell HincII).',
      'Partial digestion and double digestion for mapping.',
    ],
    advanced: [
      'Methylation interference footprinting: map protein–DNA contact (DNase I / methyl-sensitive enzymes).',
      'Engineered meganucleases and zinc-finger nucleases (pre-CRISPR precision cutters).',
    ],
    gate: {
      highYield: [
        'Type II = site-specific (lab); sticky vs blunt.',
        'EcoRI = GAATTC → 5′ overhang (sticky).',
        'Restriction–modification: methylation protects self-DNA.',
        'RFLP = restriction + Southern blot.',
        'Isoschizomers = same recognition sequence.',
      ],
      traps: [
        'Sticky ends have 5′ OR 3′ overhangs (EcoRI = 5′; some like PstI = 3′) — a direction question.',
        'Methylation PREVENTS cutting (protects host) — it does not "activate" the enzyme.',
        'RFLP detects LENGTH polymorphism (insertion/deletion), not point mutation (unless it creates/destroys a site).',
      ],
    },
    examples: [
      'Sickle cell: HbA has HincII site (CTCGAG); HbS mutates it → different RFLP pattern (diagnosis).',
      'EcoRI-cut + BamHI-cut vectors → directional cloning (no self-ligation).'],
    formulas: [],
    keyPoints: [
      'Type II = site-specific (lab).',
      'EcoRI GAATTC → 5′ sticky.',
      'Methylation protects self-DNA.',
      'RFLP = restriction + Southern.',
      'Isoschizomers = same site.',
    ],
    revision: {
      remember: 'Type II cuts; EcoRI 5′-sticky; methylation protects; RFLP = Southern.',
      mistakes: ['Methylation activating (it prevents).'],
      summary: 'Restriction types + sticky/blunt + methylation + RFLP + isoschizomers.',
    },
    related: ['rdt-cloning', 'rdt-sequencing', 'mol-replication'],
  },
  {
    id: 'rdt-vectors',
    subject: 'recombinant-dna',
    name: 'Cloning Vectors & Hosts',
    level: 1,
    priority: 'high',
    ord: 2,
    short: 'Plasmids, phages, cosmids, BACs, YACs — the DNA taxis.',
    basic: {
      what: 'A cloning vector carries foreign DNA into a host cell and replicates. Requirements: origin of replication (ori), selectable marker (antibiotic resistance), multiple cloning site (MCS), and a size range matching the insert.',
      why: 'Vector choice (insert size, host, copy number) is a GATE decision question.',
      how: 'Plasmid (1–10 kb insert; E. coli; high copy). Cosmid (30–45 kb; cos site + plasmid; E. coli). BAC (Bacterial Artificial Chromosome; 100–300 kb; F-factor; E. coli). YAC (Yeast Artificial Chromosome; 100 kb–2 Mb; yeast telomeres + centromere). Phage λ (10–20 kb; packaging limits).',
      where: 'Genome projects, gene cloning, expression, gene therapy vectors.',
    },
    college: [
      'Selectable markers: ampicillin (bla), kanamycin (nptII), tetracycline; blue-white (lacZ α-complementation + X-gal: white = insert).',
      'MCS: cluster of restriction sites within a marker/reporter for directional cloning.',
      'Expression vectors: promoter (T7, lac, GFP), RBS (bacteria), Kozak (euk), tag (His, GFP), signal peptide.',
      'Shuttle vectors: work in two hosts (ori + markers for both; e.g. E. coli + yeast 2 μ).',
    ],
    advanced: [
      'Phagemid: plasmid + phage packaging → single-stranded DNA (phage display).',
      'Viral vectors for gene therapy: AAV, lentivirus, adenovirus, retrovirus (see Molecular/Cell).',
    ],
    gate: {
      highYield: [
        'Vector → insert size → host table (plasmid 1–10, cosmid 30–45, BAC 100–300, YAC up to 2 Mb).',
        'Blue-white: lacZ α-complementation; white = insert in MCS.',
        'Shuttle = two hosts (two ori/markers).',
        'Expression: promoter + RBS/Kozak + tag + signal.',
      ],
      traps: [
        'YAC is YEAST (not bacterial) — the largest-insert vector; BAC is BACTERIAL (F-factor).',
        'Cosmid needs a COS site (phage packaging) + plasmid ori — a hybrid.',
        'A vector needs an ORI to replicate — a "minimum requirements" question.',
      ],
    },
    examples: [
      'Human genome project: BAC/YAC libraries for large-insert mapping.',
      'pUC19: classic plasmid, lacZ α-screening, AmpR.'],
    formulas: [],
    keyPoints: [
      'Plasmid 1–10 kb; cosmid 30–45; BAC 100–300; YAC ≤2 Mb (yeast).',
      'Vector minimums: ori + marker + MCS.',
      'Blue-white: white = insert.',
      'Shuttle = two hosts.',
    ],
    revision: {
      remember: 'Plasmid<cosmid<BAC<YAC; white = insert; shuttle = 2 hosts.',
      mistakes: ['Calling YAC bacterial.'],
      summary: 'Vector catalog (size/host) + minimum requirements + screening + expression features.',
    },
    related: ['rdt-restriction', 'rdt-cloning', 'rdt-libraries'],
  },
  {
    id: 'rdt-pcr',
    subject: 'recombinant-dna',
    name: 'PCR & Its Variants',
    level: 1,
    priority: 'high',
    ord: 3,
    short: 'Exponential DNA amplification and the calculations.',
    basic: {
      what: 'PCR (Polymerase Chain Reaction) amplifies a specific DNA region exponentially using primers, dNTPs, Taq polymerase and thermal cycling. Mullis (1983); Nobel 1993.',
      why: 'PCR is the most-used biotech tool; its math (2^n) and variants are GATE core.',
      how: '3 steps × n cycles: denature (94–98°C) → anneal (50–65°C, primer Tm) → extend (72°C, Taq). Product = 2^n (theoretical); plateau at high n (reagent/competition). ~30 cycles = 10^9-fold.',
      where: 'Diagnostics, genotyping, forensics, cloning, NGS library prep.',
    },
    college: [
      'Tm calculation: Tm = 2(A+T) + 4(G+C) (short oligos); longer: 64.9 + 0.41(%GC) + 500/L + 16.6 log[K+].',
      'Variants: RT-PCR (RNA → cDNA → PCR); qPCR/real-time (CT threshold, 2^-ΔΔCt); inverse PCR (unknown flanking); assembly/overlap; RACE (ends); nested (sensitivity); hot-start (fidelity).',
      'qPCR: CT (cycle threshold); ΔΔCt for relative quantification; standard curve for absolute.',
      'Taq: thermostable (T. aquaticus), 5′→3′ only (no 3′→5′ proofreading → error-prone); Pfu (proofreading) for cloning.',
    ],
    advanced: [
      'Digital PCR: absolute quantification without standard curve (partitioning).',
      'Long-range PCR and isothermal methods (LAMP, RPA) for field diagnostics.',
    ],
    gate: {
      highYield: [
        'PCR steps + temperatures (denature 95, anneal ~55, extend 72).',
        'Amplification = 2^n; 30 cycles ≈ 10^9.',
        'Tm formula (2AT+4GC for short).',
        'RT-PCR = RNA to cDNA; qPCR = CT/ΔΔCt.',
        'Taq = no proofreading; Pfu = proofreading.',
      ],
      traps: [
        'PCR needs 2 PRIMERS (forward + reverse) — a "minimum components" question.',
        'qPCR CT: LOWER CT = MORE starting template (not less) — an inverse trap.',
        'RT-PCR vs reverse-transcription-PCR naming confusion: "RT-PCR" usually means reverse-transcription PCR (RNA target).',
        'Taq lacks 3′→5′ exonuclease → accumulates errors (use Pfu for cloning).',
      ],
    },
    examples: [
      '1 template → 30 cycles → ~2^30 ≈ 10^9 copies.',
      'SARS-CoV-2 RT-qPCR: CT 25 = high viral load; CT 38 = low/late.'],
    formulas: [
      { name: 'Amplification', expr: 'N = N0 × 2^n (theoretical)' },
      { name: 'Tm (short)', expr: 'Tm = 2(A+T) + 4(G+C)' },
      { name: 'Relative qPCR', expr: '2^(−ΔΔCt)' },
    ],
    keyPoints: [
      'Denature 95 / anneal ~55 / extend 72.',
      '2^n amplification; 30 ≈ 10^9.',
      'Tm = 2AT + 4GC (short).',
      'RT-PCR = RNA→cDNA; qPCR = CT/ΔΔCt.',
      'Taq no proofreading; Pfu yes.',
    ],
    revision: {
      remember: '95/55/72; 2^n; Tm=2AT+4GC; low CT = more template.',
      mistakes: ['High CT = more template (it is less).'],
      summary: 'PCR mechanism + math + Tm + variants (RT/q/digital) + polymerase choices.',
    },
    related: ['rdt-restriction', 'mol-transcription', 'num-pcr'],
  },
  {
    id: 'rdt-cloning',
    subject: 'recombinant-dna',
    name: 'Cloning & Expression Workflow',
    level: 2,
    priority: 'high',
    ord: 4,
    short: 'From gene to protein: the complete pipeline.',
    basic: {
      what: 'Molecular cloning inserts a gene into a vector, transforms a host, selects clones, verifies the insert, and (for expression) produces the protein. It is the central skill of biotech.',
      why: 'The cloning workflow + verification steps are GATE process questions.',
      how: '1) Isolate gene (PCR with restriction sites or synthetic). 2) Digest vector + insert (same enzyme → sticky; or two enzymes → directional). 3) Ligate (DNA ligase, ATP). 4) Transform (heat-shock 42°C / electroporation; CaCl2 competent). 5) Select (antibiotic plate). 6) Screen (blue-white, colony PCR). 7) Verify (restriction digest, sequencing). 8) Express (induce; IPTG for lac/T7).',
      where: 'Recombinant protein production, gene function, strain engineering.',
    },
    college: [
      'Ligation: sticky (efficient, 1:1) vs blunt (less efficient, need high concentration); phosphokinetase (blunt ends).',
      'Transformation efficiency: CFU/µg DNA; heat-shock (CaCl2, 42°C, 45–90 s) vs electroporation (higher efficiency).',
      'Colony PCR + restriction digest + Sanger sequencing = the 3-tier verification.',
      'Expression: lac (IPTG), T7 (ISPT1), arabinose (BAD); protein tags (His, GST, MBP); inclusion bodies (E. coli) vs secreted (yeast/CHO).',
    ],
    advanced: [
      'Gateway/ClonExpress: recombination-based cloning (att sites) — scarless, directional, no restriction sites needed.',
      'Protein engineering: codon optimisation, signal peptides, fusion tags for solubility/yield.',
    ],
    gate: {
      highYield: [
        'Cloning steps in order (isolate → digest → ligate → transform → select → verify → express).',
        'Directional cloning = two different enzymes (no self-ligation).',
        'Heat-shock: CaCl2 + 42°C (competent cells).',
        'IPTG induces lac/T7 (non-metabolisable lactose analog).',
        '3-tier verification: colony PCR + digest + sequencing.',
      ],
      traps: [
        'Ligation needs ATP (DNA ligase uses ATP) — a "what is required" question.',
        'A self-ligating vector (one enzyme) gives insert in BOTH orientations + empty vector — why directional (2 enzymes) is preferred.',
        'IPTG is NOT metabolised (unlike lactose) → no catabolite repression, constant induction.',
      ],
    },
    examples: [
      'Insulin: human preproinsulin gene in E. coli (two chains) → chemical linking → insulin (first recombinant human protein, 1978/1982).',
      'GFP (Aequorea victoria) cloned into vectors → reporter workhorse.'],
    formulas: [],
    keyPoints: [
      'Order: isolate→digest→ligate→transform→select→verify→express.',
      'Directional = 2 enzymes.',
      'CaCl2 + 42°C heat-shock.',
      'IPTG = non-metabolised inducer.',
      'Verify: PCR + digest + sequence.',
    ],
    revision: {
      remember: 'The 7 steps; 2 enzymes = directional; 42°C shock; IPTG.',
      mistakes: ['Ligation without ATP.'],
      summary: 'Complete cloning pipeline + directional logic + transformation + verification + expression.',
    },
    related: ['rdt-vectors', 'rdt-pcr', 'rdt-restriction'],
  },
  {
    id: 'rdt-sequencing',
    subject: 'recombinant-dna',
    name: 'DNA Sequencing: Sanger & NGS',
    level: 2,
    priority: 'high',
    ord: 5,
    short: 'Reading the genome: classic and next-generation.',
    basic: {
      what: 'Sequencing determines the nucleotide order. Sanger (chain-termination, dideoxy) reads ~800–1000 bp; NGS (Illumina, etc.) reads millions of short reads in parallel.',
      why: 'Sanger logic (ddNTP termination) and NGS principles are GATE material; sequencing underlies genomics.',
      how: 'Sanger: 4 reactions (or 1 with 4 coloured ddNTPs) — DNA pol stops at ddNTP (no 3′-OH) → fragments of every length → size separation (capillary) → sequence. NGS (Illumina): bridge amplification (clonal clusters) → sequencing-by-synthesis (reversible-terminator fluorescent ddNTP) → image each cycle.',
      where: 'Gene verification, mutation detection, whole-genome, RNA-seq, metagenomics.',
    },
    college: [
      'Sanger: ddNTP = dideoxy (no 3′-OH) → termination; capillary electrophoresis; ~99.99% accuracy per base.',
      'Illumina: cluster generation (bridge PCR) → SBS with reversible terminators → 150 bp × paired-end typical; high throughput, high error at high GC.',
      'Other NGS: PacBio (SMRT, long reads, no PCR), Oxford Nanopore (ionic current, real-time, very long).',
      'Read mapping (BWA), variant calling (GATK), assembly (de Bruijn for short; OLC for long).',
    ],
    advanced: [
      'Long-read advantages: span repeats, phase variants, detect structural variants; lower per-base accuracy but higher consensus.',
      'Single-molecule, targeted (amplicon), and trioseq (RNA) applications.',
    ],
    gate: {
      highYield: [
        'Sanger: ddNTP (no 3′-OH) → termination; capillary.',
        'Illumina: bridge PCR + SBS (reversible terminators).',
        'PacBio/Nanopore: long reads (structural variants, repeats).',
        'Sanger ~1 kb read; NGS short (100–300 bp) high throughput.',
      ],
      traps: [
        'ddNTP lacks the 3′-OH (not the 5′) — the termination chemistry trap.',
        'Illumina is NOT single-molecule (it uses clonal clusters) — a platform trap.',
        'Long reads have LOWER per-base accuracy but resolve structure better — a nuance question.',
      ],
    },
    examples: [
      'First human genome: Sanger (2003); now NGS dominates (cost ~$100–600/genome).',
      'Nanopore: real-time pathogen sequencing at field stations.'],
    formulas: [],
    keyPoints: [
      'Sanger: ddNTP (no 3′-OH) termination; ~1 kb.',
      'Illumina: clusters + SBS (reversible).',
      'Long reads (PacBio/Nano): repeats + SVs.',
      'Short = high accuracy/throughput; long = structure.',
    ],
    revision: {
      remember: 'ddNTP no 3′-OH; Illumina clusters+SBS; long = repeats.',
      mistakes: ['ddNTP missing 5′-OH (it is 3′).'],
      summary: 'Sanger chemistry + NGS platforms + read-length trade-offs.',
    },
    related: ['rdt-pcr', 'inf-genome', 'mol-replication'],
  },
  {
    id: 'rdt-libraries',
    subject: 'recombinant-dna',
    name: 'Genomic & cDNA Libraries',
    level: 3,
    priority: 'medium',
    ord: 6,
    short: 'Storing and finding genes: the library concept.',
    basic: {
      what: 'A gene library stores a population’s DNA fragments in vectors. Genomic library = whole genome (with introns, repeats). cDNA library = expressed genes only (from mRNA, no introns).',
      why: 'Library logic (genomic vs cDNA, size, screening) is GATE material; the basis of gene discovery.',
      how: 'Genomic: digest genome → clone in BAC/YAC/plasmid → store. cDNA: mRNA → (reverse transcriptase) → cDNA → clone. Screening: colony/hybridisation (probe), expression (antibody), or sequence (shotgun).',
      where: 'Gene cloning, genome projects, functional genomics.',
    },
    college: [
      'Genomic vs cDNA: genomic has introns + regulatory; cDNA has only exons (coding) — cDNA for expression in bacteria (no splicing).',
      'Library size (Covariance formula): N = ln(1−P)/ln(1−f); for 99% probability (P=0.99) of containing a fragment of fraction f, N ≈ ln(0.01)/ln(1−f). Human genome: ~3–5 ×10^4 BAC clones.',
      'Hybridisation screening: labelled probe (DNA/RNA) → colony lift → Southern-style (colony blot) → hybridise → positive colony = pick.',
      'Expression library: cDNA in a vector that can be transcribed/translated; screen by protein (antibody) or activity.',
    ],
    advanced: [
      'EST (Expressed Sequence Tag): 500 bp cDNA end-sequenced → gene catalogue (pre-genome-sequencing era).',
      'Representational Difference Analysis (RDA): subtractive hybridisation to find differentially expressed sequences.',
    ],
    gate: {
      highYield: [
        'Genomic (introns, whole) vs cDNA (exons, expressed).',
        'cDNA for BACTERIAL expression (no splicing in bacteria).',
        'Library size formula (Covariance).',
        'Hybridisation screening (probe + colony blot).',
      ],
      traps: [
        'Bacteria CANNOT splice introns — a genomic (eukaryotic) insert won’t express correctly in E. coli; use cDNA — a classic logic trap.',
        'cDNA library represents only the CELL TYPE’s expressed genes (not the whole genome) — a "what is in the library" question.',
      ],
    },
    examples: [
      'Human genome: ~10^5 BAC clones (genomic library) for the international project.',
      'Insulin gene originally cloned from a HUMAN cDNA library (not genomic) for expression.'],
    formulas: [
      { name: 'Library size (Covariance)', expr: 'N = ln(1−P) / ln(1−f)' },
    ],
    keyPoints: [
      'Genomic = whole (introns); cDNA = expressed (exons).',
      'cDNA for bacterial expression (no splicing).',
      'N = ln(1−P)/ln(1−f).',
      'Screen by probe (DNA) or antibody (protein).',
    ],
    revision: {
      remember: 'Genomic whole, cDNA expressed; bacteria can’t splice; Covariance formula.',
      mistakes: ['Expressing a genomic eukaryotic gene in E. coli.'],
      summary: 'Library types + size math + screening + expression logic.',
    },
    related: ['rdt-vectors', 'rdt-sequencing', 'mol-transcription'],
  },
  {
    id: 'rdt-crispr',
    subject: 'recombinant-dna',
    name: 'CRISPR-Cas9 & Gene Editing',
    level: 3,
    priority: 'high',
    ord: 7,
    short: 'The programmable genome editor.',
    basic: {
      what: 'CRISPR-Cas9 is a programmable DNA-cutting system: a guide RNA (gRNA) directs Cas9 to a matching 20 nt sequence next to a PAM (NGG), where Cas9 makes a double-strand break. The cell repairs by NHEJ (knockout) or HDR (knock-in).',
      why: 'CRISPR is the defining biotech tool; mechanism and applications are GATE core.',
      how: 'Design sgRNA (20 nt + scaffold) → deliver (RNP, plasmid, viral) → Cas9 cuts at target+PAM → DSB → NHEJ (indels → frameshift knockout) or HDR (donor template → precise edit). Off-target: guide similarity → mitigation (high-fidelity Cas9, nickase, truncated guides).',
      where: 'Gene knockout/knock-in, base editing, CRISPRi/a (regulation), diagnostics (SHERLOCK, DETECTR), therapy (Casgevy).',
    },
    college: [
      'PAM: 5′-NGG-3′ for SpCas9 (required; no PAM = no cut).',
      'Base editors: CBE (C→T), ABE (A→G) — no DSB; prime editor (pegRNA) — no DSB, broader edits.',
      'CRISPRi (dCas9-KRAB = repress), CRISPRa (dCas9-VP64 = activate) — no cut, reversible.',
      'Diagnostics: SHERLOCK (Cas13, RNA target, signal amplification); DETECTR (Cas12, DNA target).',
      'Therapy: Casgevy (exagamglogene autotemcel, 2023) — CRISPR-edited autologous CD34+ for sickle cell/beta-thalassaemia.',
    ],
    advanced: [
      'Multiplex editing: multiple sgRNAs; epigenome editing (dCas9-DNMT3A/TET1).',
      'Delivery: AAV (in vivo, size limit), LNP (lipid nanoparticle, base editors), electroporation (ex vivo cells).',
    ],
    gate: {
      highYield: [
        'CRISPR steps: gRNA + PAM (NGG) + Cas9 → DSB → NHEJ/HDR.',
        'NHEJ = KO (indels); HDR = KI (donor).',
        'Base/prime editing = NO DSB.',
        'CRISPRi/a = dCas9 (no cut).',
        'SHERLOCK = Cas13 (RNA); DETECTR = Cas12 (DNA).',
        'PAM = NGG (SpCas9); required.',
      ],
      traps: [
        'No PAM = no cut (absolute requirement) — a "will it edit?" question.',
        'CRISPRi does NOT cut (dCas9) — a mechanism trap.',
        'SHERLOCK targets RNA (Cas13); DETECTR targets DNA (Cas12) — a swap trap.',
        'NHEJ is error-PRONE (indels); HDR is precise but less efficient (needs homology arm + S/G2).',
      ],
    },
    examples: [
      'Casgevy: CCR5 knockout in autologous HSCs → functional α-thalassaemia-in-haemoglobinopathy protection.',
      'SHERLOCK for SARS-CoV-2: isothermal, field-deployable.'],
    formulas: [],
    keyPoints: [
      'gRNA + PAM (NGG) + Cas9 → DSB.',
      'NHEJ = KO; HDR = KI.',
      'Base/prime = no DSB; CRISPRi/a = dCas9.',
      'SHERLOCK (Cas13/RNA); DETECTR (Cas12/DNA).',
    ],
    revision: {
      remember: 'PAM NGG; NHEJ KO, HDR KI; base no-cut; SHERLOCK=RNA/Cas13.',
      mistakes: ['Cutting without PAM; SHERLOCK/DETECTR swap.'],
      summary: 'CRISPR mechanism + editing outcomes + base/prime + CRISPRi/a + diagnostics.',
    },
    related: ['mol-ncrna', 'plb-editing', 'rdt-restriction'],
  },
  {
    id: 'rdt-gate',
    subject: 'recombinant-dna',
    name: 'GATE Focus: Recombinant DNA',
    level: 4,
    priority: 'high',
    ord: 8,
    short: 'Enzymes, vectors, PCR and CRISPR — the core banks.',
    basic: {
      what: 'GATE recombinant DNA = restriction/vector/PCR/CRISPR banks + cloning workflow + verification logic.',
      why: 'The most tool-dense subject; high recall yield with precision traps.',
      how: 'Drill: enzyme end types, vector sizes, PCR temps + math, CRISPR PAM + outcomes, cloning order.',
      where: 'GATE BT paper.',
    },
    college: [
      'Enzyme bank: EcoRI (5′-sticky, GAATTC), SmaI (blunt), BamHI (GGATCC), HindIII (AAGCTT).',
      'Vector bank: plasmid 1–10, cosmid 30–45, BAC 100–300, YAC ≤2 Mb (yeast).',
      'PCR: 95/55/72; 2^n; Tm=2AT+4GC; Taq no proofread; qPCR low CT = more template.',
      'CRISPR: PAM NGG; NHEJ KO; HDR KI; base no-cut; SHERLOCK RNA/Cas13.',
      'Cloning: isolate→digest→ligate→transform→select→verify→express; 2 enzymes = directional.',
    ],
    advanced: [
      'Multi-step: "clone a 5 kb gene into E. coli for expression" → PCR with sites → directional digest → ligate → transform → AmpR + blue-white → verify (PCR/digest/seq) → IPTG induce.',
      'Decision: vector choice by insert size.',
    ],
    gate: {
      highYield: [
        'All five banks + cloning workflow + verification.',
      ],
      traps: [
        'Sticky vs blunt end assignment.',
        'PCR temperature order (denature first).',
        'qPCR CT direction (low = more).',
        'CRISPR PAM requirement.',
      ],
    },
    examples: [
      '"5 kb insert, best vector?" → cosmid (30–45 kb range) or plasmid (if <10 kb, plasmid OK).',
      '"Which enzyme gives blunt ends?" → SmaI.'],
    formulas: [],
    keyPoints: [
      'Enzyme/vector/PCR/CRISPR/cloning banks.',
      'Precision: end types, temps, CT direction, PAM.',
    ],
    revision: {
      remember: 'Five banks + workflow + precision traps.',
      mistakes: ['End-type and CT-direction swaps.'],
      summary: 'rDNA GATE = five tool banks + cloning workflow, drilled to precision.',
    },
    related: ['rdt-restriction', 'rdt-vectors', 'rdt-pcr', 'rdt-crispr'],
  },
];

// ============ TRANSPORT PROCESSES ============
export const TOPICS_TRP: Topic[] = [
  {
    id: 'trp-momentum',
    subject: 'transport-processes',
    name: 'Momentum Transfer (Fluid Flow)',
    level: 1,
    priority: 'high',
    ord: 1,
    short: 'How fluids move: pipes, pumps and pressure drop.',
    basic: {
      what: 'Momentum transfer studies fluid motion: flow in pipes, through equipment, and the pressure needed to drive it. Laminar (smooth, Re<2100) vs turbulent (chaotic, Re>4000) flow govern the equations.',
      why: 'Pressure drop, pump selection and pipe sizing are GATE transport numericals.',
      how: 'Reynolds number Re = ρvD/μ. Laminar: Hagen–Poiseuille (ΔP = 32μvL/D²). Turbulent: Darcy–Weisbach (ΔP = f·(L/D)·(ρv²/2)); f from Moody chart/Colebrook. Bernoulli: P/ρg + v²/2g + z = const (head).',
      where: 'Piping, bioreactor feed, centrifuges, pumps.',
    },
    college: [
      'Continuity: Q = Av (mass conservation); for incompressible, A1v1 = A2v2.',
      'Head: static (z) + velocity (v²/2g) + pressure (P/ρg); pump adds head, friction removes it.',
      'Pumps: centrifugal (dynamic, high flow low head) vs positive-displacement (low flow high head); NPSH (net positive suction head) prevents cavitation.',
      'Minor losses: fittings, valves (K-factors); total ΔP = major + minor.',
    ],
    advanced: [
      'Non-Newtonian fluids (biological: broths, blood): power-law (τ = Kγ^n), Bingham plastic (yield stress); effective viscosity changes Re and ΔP.',
      'Transient and two-phase flow in bioprocesses (aerated bioreactors).',
    ],
    gate: {
      highYield: [
        'Re = ρvD/μ; laminar <2100, turbulent >4000.',
        'Hagen–Poiseuille (laminar) vs Darcy–Weisbach (turbulent).',
        'Bernoulli head terms (static/velocity/pressure).',
        'NPSH and cavitation.',
        'Centrifugal vs positive-displacement pump choice.',
      ],
      traps: [
        'Hagen–Poiseuille is LAMINAR only (ΔP ∝ v); Darcy is turbulent (ΔP ∝ v²) — a flow-regime trap.',
        'Reynolds number: higher Re = MORE turbulent (not less).',
        'NPSH must EXCEED the fluid’s NPSHr (required) or the pump cavitates — a direction trap.',
      ],
    },
    examples: [
      'A 2 cm pipe, v = 1 m/s, water: Re = 1000×1×0.02/0.001 = 20000 → turbulent.',
      'Bioreactor feed pump: choose centrifugal for high-flow broth delivery.'],
    formulas: [
      { name: 'Reynolds', expr: 'Re = ρvD/μ' },
      { name: 'Hagen–Poiseuille', expr: 'ΔP = 32μvL/D² (laminar)' },
      { name: 'Darcy–Weisbach', expr: 'ΔP = f(L/D)(ρv²/2)' },
      { name: 'Bernoulli', expr: 'P/ρg + v²/2g + z = const' },
    ],
    keyPoints: [
      'Re = ρvD/μ; laminar <2100, turbulent >4000.',
      'Laminar: Hagen–Poiseuille; turbulent: Darcy–Weisbach.',
      'Bernoulli = head conservation.',
      'NPSH > NPSHr (avoid cavitation).',
    ],
    revision: {
      remember: 'Re regimes; Hagen laminar, Darcy turbulent; NPSH > NPSHr.',
      mistakes: ['Using Hagen for turbulent flow.'],
      summary: 'Fluid flow: Re + pressure drop (both regimes) + Bernoulli + pumps + NPSH.',
    },
    related: ['trp-heat', 'trp-mass', 'bae-oxygen'],
  },
  {
    id: 'trp-heat',
    subject: 'transport-processes',
    name: 'Heat Transfer',
    level: 1,
    priority: 'high',
    ord: 2,
    short: 'Conduction, convection and sterilisation heating.',
    basic: {
      what: 'Heat transfer moves thermal energy by conduction (through material), convection (fluid motion), and radiation. In biotech: sterilisation heating, bioreactor cooling, pasteurisation.',
      why: 'Sterilisation time-temperature (D-value) and heat exchanger design are GATE numericals.',
      how: 'Conduction: Q = kAΔT/L (Fourier). Convection: Q = hAΔT (Newton cooling); h depends on flow (Re, Pr). Overall: 1/U = 1/h_i + R_wall + 1/h_o (series resistances).',
      where: 'Autoclave sizing, heat exchangers, bioreactor jackets, pasteurisation.',
    },
    college: [
      'Heat exchangers: double-pipe, shell-and-tube, plate; LMTD (log-mean temperature difference) for sizing.',
      'Bioreactor heat removal: jacket + internal coil; heat generated by metabolism (Q_gen) must be removed.',
      'Foam and fouling: fouling factor (R_f) added to resistance; reduces U over time.',
      'Thermal properties of broths: k, ρ, cp (often close to water but viscous).',
    ],
    advanced: [
      'Unsteady heating: penetration time (t = L²/α) for thick products; batch sterilisation dynamics.',
      'Multiphase (aerated) heat transfer: gas holdup reduces liquid-side h.',
    ],
    gate: {
      highYield: [
        'Conduction (Fourier) vs convection (Newton) vs radiation.',
        'Overall U and series resistances (1/U sum).',
        'LMTD for exchanger sizing.',
        'Bioreactor: Q_gen (metabolic) vs Q_removed (jacket).',
        'Fouling reduces U (adds R_f).',
      ],
      traps: [
        'Conduction is through STATIONARY material; convection needs FLUID MOTION — a mechanism trap.',
        'LMTD is used when temperatures CHANGE along the exchanger (not constant) — an applicability question.',
        'Adding fouling RESISTANCE DECREASES U (not increases) — a direction trap.',
      ],
    },
    examples: [
      'Sterilisation: heat broth to 121°C; hold time set by D-value of the most-resistant contaminant.',
      'Bioreactor jacket removes ~metabolic heat; CO2 evolution also cools slightly.'],
    formulas: [
      { name: 'Conduction', expr: 'Q = kAΔT/L' },
      { name: 'Convection', expr: 'Q = hAΔT' },
      { name: 'Overall U', expr: '1/U = 1/h_i + R_wall + R_f + 1/h_o' },
      { name: 'LMTD', expr: 'ΔT_lm = (ΔT1 − ΔT2)/ln(ΔT1/ΔT2)' },
    ],
    keyPoints: [
      'Conduction (Fourier) / convection (Newton) / radiation.',
      '1/U = sum of resistances (series).',
      'LMTD sizes exchangers.',
      'Bioreactor: metabolic heat vs jacket removal.',
    ],
    revision: {
      remember: 'Fourier/Newton; 1/U = ΣR; LMTD; fouling ↓U.',
      mistakes: ['Fouling increasing U.'],
      summary: 'Heat transfer modes + overall U + LMTD + bioreactor thermal balance.',
    },
    related: ['trp-momentum', 'trp-mass', 'mic-sterilization'],
  },
  {
    id: 'trp-mass',
    subject: 'transport-processes',
    name: 'Mass Transfer',
    level: 2,
    priority: 'high',
    ord: 3,
    short: 'Diffusion, distillation and the molar driving force.',
    basic: {
      what: 'Mass transfer moves species by diffusion (molecular) or convection (bulk flow). In biotech: O2 into liquid (kLa), distillation of solvents, absorption, membrane separation.',
      why: 'kLa (O2 transfer) is the central bioreaction concept; distillation/absorption are GATE unit ops.',
      how: 'Fick’s law: J = −D·dc/dx (diffusion flux). Gas-liquid: OTR = kLa(C*−CL). Distillation: Raoult’s law + relative volatility (α); McCabe–Thiele for stages. Absorption: solute transfers gas→liquid (scrubbers).',
      where: 'Aeration, solvent recovery, gas scrubbing, membrane processes.',
    },
    college: [
      'Distillation: relative volatility α = (yA/xA)/(yB/xB); α>1 separable; total reflux (minimum stages, Fenske) vs minimum reflux (infinite stages, Underwood).',
      'McCabe–Thiele: graphical stage-by-stage (equilibrium + operating lines); feed line (q-line).',
      'Absorption: absorption factor A = L/(mG); A>1 for high recovery.',
      'Membranes: dialysis, UF, NF, RO (size-based); permeate vs retentate.',
      'Stripping/stripping factor for desorption.',
    ],
    advanced: [
      'Rate-based (non-equilibrium) distillation models; structured packings (HETP lower than trays).',
      'Multi-component (FUG: Fenske–Underwood–Gilliland) shortcut design.',
    ],
    gate: {
      highYield: [
        'Fick’s law; OTR = kLa(C*−CL).',
        'Relative volatility α; α>1 = separable.',
        'Total reflux = minimum stages (Fenske); min reflux = infinite stages (Underwood).',
        'Absorption factor A = L/mG; A>1 for recovery.',
        'Membrane ladder (MF/UF/NF/RO).',
      ],
      traps: [
        'α = 1 means NO separation (no volatility difference) — a "can you separate?" question.',
        'Total reflux gives MINIMUM stages but INFINITE distillate (no product) — an operability trap.',
        'Increasing A (more liquid) INCREASES absorption recovery — a direction question.',
      ],
    },
    examples: [
      'Ethanol-water distillation: α ≈ 1 at azeotrope (~95%) → needs azeotropic/extractive distillation or molecular sieves.',
      'Bioreactor O2: kLa 2 h⁻¹, C*−CL = 0.5 → OTR = 1.0 (units consistent).'],
    formulas: [
      { name: 'Fick', expr: 'J = −D dc/dx' },
      { name: 'OTR', expr: 'OTR = kLa(C* − CL)' },
      { name: 'Relative volatility', expr: 'α = (yA/xA)/(yB/xB)' },
      { name: 'Fenske', expr: 'N_min = ln[(xD/(1−xD))·((1−xB)/xB)] / ln α' },
    ],
    keyPoints: [
      'Fick + OTR = kLa(C*−CL).',
      'α>1 separable; α=1 impossible.',
      'Fenske = min stages (total reflux); Underwood = min reflux.',
      'A = L/mG (absorption).',
    ],
    revision: {
      remember: 'Fick/OTR; α>1; Fenske min stages; A=L/mG.',
      mistakes: ['α=1 separation.'],
      summary: 'Mass transfer: diffusion + OTR + distillation (α, FUG) + absorption + membranes.',
    },
    related: ['bae-oxygen', 'trp-momentum', 'trp-heat'],
  },
  {
    id: 'trp-separation',
    subject: 'transport-processes',
    name: 'Separation Processes (Distillation, Filtration, Extraction)',
    level: 2,
    priority: 'medium',
    ord: 4,
    short: 'The unit operations that purify bulk streams.',
    basic: {
      what: 'Separation processes split mixtures: distillation (volatility), filtration (size), extraction (solubility), crystallisation (saturation), adsorption (surface). They follow the bioreactor in bulk downstream.',
      why: 'Unit operation selection + operating principles are GATE process questions.',
      how: 'Distillation: column, trays/packing, reflux. Filtration: pressure-driven (plate-and-frame, leaf, centrifugal); cake filtration equation (constant pressure: t/V = αμc/2ΔP·V² + Rm/ΔP·V). Extraction: liquid-liquid (counter-current), distribution coefficient.',
      where: 'Solvent recovery, product concentration, purification, water treatment.',
    },
    college: [
      'Filtration: constant-pressure cake (linear t vs V); constant-rate (ΔP rises); filter aid (diatomaceous earth).',
      'Liquid-liquid extraction: distribution coefficient K = c_org/c_aq; counter-current > single-stage; extraction factor E = K·(org flow/aq flow).',
      'Crystallisation: supersaturation (metastable zone); nucleation vs growth; purity vs yield trade-off.',
      'Adsorption: isotherms (Langmuir, Freundlich); fixed-bed (breakthrough curve); regeneration (heat/solvent).',
    ],
    advanced: [
      'Membrane distillation and pervaporation (hybrid separation).',
      'Scale-up of crystallisation (population balance models).',
    ],
    gate: {
      highYield: [
        'Unit operation → separation principle table.',
        'Filtration: constant-pressure t vs V (linear, quadratic term).',
        'Extraction factor E = K·(org/aq); counter-current superiority.',
        'Crystallisation: supersaturation + metastable zone.',
        'Adsorption isotherms (Langmuir/Freundlich).',
      ],
      traps: [
        'Constant-RATE filtration: ΔP must INCREASE over time (cake builds) — vs constant-PRESSURE where rate falls — a regime trap.',
        'Extraction factor E>1 needed for good recovery with finite stages — a design threshold.',
        'Langmuir assumes MONOLAYER on uniform sites (not multilayer like BET) — a model-assumption question.',
      ],
    },
    examples: [
      'Antibiotic recovery: liquid-liquid extraction (butyl acetate) → counter-current mixer-settlers.',
      'Water: activated carbon adsorption (isotherm) for organics removal.'],
    formulas: [
      { name: 'Cake filtration (const P)', expr: 't/V = (αμc/2ΔP)·V + Rm/ΔP' },
      { name: 'Extraction factor', expr: 'E = K·(O/A)' },
      { name: 'Langmuir', expr: 'q = qmax·K·C/(1 + K·C)' },
    ],
    keyPoints: [
      'Unit op → principle table.',
      'Filtration: const-P t-V linear; const-R ΔP rises.',
      'E = K·(O/A); counter-current better.',
      'Crystallisation = supersaturation + metastable zone.',
      'Langmuir = monolayer, uniform.',
    ],
    revision: {
      remember: 'Op-principle table; const-P t-V; E=K·O/A; Langmuir monolayer.',
      mistakes: ['Constant-rate ΔP falling.'],
      summary: 'Separation unit ops: distillation/filtration/extraction/crystallisation/adsorption with operating logic.',
    },
    related: ['trp-mass', 'pro-separation', 'pro-downstream'],
  },
  {
    id: 'trp-control',
    subject: 'transport-processes',
    name: 'Process Control & Instrumentation',
    level: 3,
    priority: 'high',
    ord: 5,
    short: 'Feedback, PID and keeping processes on target.',
    basic: {
      what: 'Process control keeps variables (T, P, flow, level, pH, DO) at setpoints using sensors + controllers + actuators. The classic is the PID feedback loop.',
      why: 'Control theory (PID, transfer functions, stability) is a GATE transport/electrical overlap.',
      how: 'Sensors measure → controller computes error (e = setpoint − measured) → actuator (valve, pump, heater) corrects. PID: u = Kp·e + Ki∫e dt + Kd·de/dt. Transfer function G(s) relates input to output; stability via poles (left half-plane).',
      where: 'Bioreactors, distillation columns, any continuous process.',
    },
    college: [
      'First-order + dead time (FOPDT): G(s) = K·e^(−θs)/(τs+1); most process units look like this.',
      'PID tuning: Ziegler–Nichols (ultimate gain/critical oscillation); λ-tuning; IMC.',
      'Cascaded control: inner (fast) + outer (slow) loops; feedforward (anticipate disturbance).',
      'Stability: Routh–Hurwitz, Nyquist; gain/phase margin.',
      'Control structures: feedback, cascade, feedforward, ratio, split-range.',
    ],
    advanced: [
      'Model predictive control (MPC): optimise over a horizon with constraints (multi-variable bioprocesses).',
      'Soft sensors and data-driven (ML) control for non-measurable states (biomass).',
    ],
    gate: {
      highYield: [
        'PID terms: P (speed), I (remove offset), D (damp).',
        'FOPDT: K, τ, θ (the 3 parameters).',
        'Cascaded: inner faster; feedforward anticipates.',
        'Stability: poles in LHP; gain/phase margin.',
        'Ziegler–Nichols from ultimate gain.',
      ],
      traps: [
        'Pure P control leaves steady-state OFFSET (I removes it) — a classic true/false.',
        'Derivative acts on the RATE of error (not the error) — and is noisy (differentiates noise) — a role trap.',
        'Cascaded: the INNER loop must be FASTER than the outer — a sequencing trap.',
      ],
    },
    examples: [
      'Bioreactor DO control: cascade (agitation inner, aeration outer) to hit 30% saturation.',
      'Distillation column: temperature cascade (reflux flow inner) for purity control.'],
    formulas: [
      { name: 'PID', expr: 'u = Kp·e + Ki∫e dt + Kd·de/dt' },
      { name: 'FOPDT', expr: 'G(s) = K·e^(−θs)/(τs+1)' },
    ],
    keyPoints: [
      'PID: P speed, I offset, D damp.',
      'FOPDT: K, τ, θ.',
      'Cascade inner faster; feedforward anticipates.',
      'Stability: LHP poles; margins.',
    ],
    revision: {
      remember: 'PID roles; FOPDT K-τ-θ; cascade inner-fast; P leaves offset.',
      mistakes: ['P control zero-offset claim.'],
      summary: 'Process control: PID + FOPDT + cascade/feedforward + stability basics.',
    },
    related: ['ins-feedback', 'trp-momentum', 'trp-heat'],
  },
  {
    id: 'trp-reactors',
    subject: 'transport-processes',
    name: 'Ideal Reactors (PFR, CSTR) & Residence Time',
    level: 3,
    priority: 'medium',
    ord: 6,
    short: 'PFR vs CSTR design and the RTD concept.',
    basic: {
      what: 'Two ideal reactor models: PFR (plug flow, no axial mixing, fluid moves as a plug) and CSTR (perfectly mixed). Residence time distribution (RTD) describes how long fluid stays.',
      why: 'Reactor comparison (conversion, size) and RTD are GATE transport/bioreaction overlap.',
      how: 'PFR: dX/dV = −rA/FA (differential); CSTR: V = FA0·X/(−rA) (algebraic). Same reaction: PFR needs LESS volume than CSTR for positive-order kinetics (concentration stays higher along PFR).',
      where: 'Chemical/bio-reactor design, sterilisation tubular units.',
    },
    college: [
      'First-order: PFR V = (v0/k)·ln(1/(1−X)); CSTR V = v0·X/k. PFR smaller for X>0.',
      'RTD: E(t) (density), F(t) (cumulative); mean residence time t̄ = ∫t·E dt; variance σ².',
      'Ideal: PFR → δ(t−t̄) (no variance); CSTR → E(t) = (1/t̄)e^(−t/t̄) (exponential).',
      'Non-ideal: tanks-in-series (N) approaches PFR as N→∞; axial dispersion model.',
    ],
    advanced: [
      'Tracer techniques: pulse (E curve) vs step (F curve); residence time in non-Newtonian/aerated systems.',
      'Bio-reaction RTD: channels/bypasses reduce effective volume; sterilisation tubular reactors (PFR-like) sized by D-value.',
    ],
    gate: {
      highYield: [
        'PFR vs CSTR volume comparison (PFR smaller, positive order).',
        'First-order design equations (PFR ln, CSTR algebraic).',
        'RTD: E, F, t̄, σ²; ideal forms (δ vs exponential).',
        'Tanks-in-series: N→∞ = PFR; N=1 = CSTR.',
      ],
      traps: [
        'CSTR concentration = OUTLET concentration (perfectly mixed) — design at outlet conditions, not inlet — a design trap.',
        'For ZERO-order kinetics, PFR and CSTR need the SAME volume (rate independent of concentration) — an exception to "PFR smaller".',
        'Mean residence time is the FIRST moment (∫tE), not the mode — a statistics trap.',
      ],
    },
    examples: [
      'Tubular steriliser: PFR; size by D-value (residence time = n·D for n-log reduction).',
      'Bioreactor with baffle/channeling: RTD shows bypass → effective volume < geometric.'],
    formulas: [
      { name: 'PFR (1st order)', expr: 'V = (v0/k)·ln(1/(1−X))' },
      { name: 'CSTR (1st order)', expr: 'V = v0·X/k' },
      { name: 'CSTR RTD', expr: 'E(t) = (1/t̄)·e^(−t/t̄)' },
    ],
    keyPoints: [
      'PFR smaller than CSTR (positive order); equal for zero-order.',
      'CSTR design at OUTLET conditions.',
      'RTD: E/F/t̄/σ²; ideal δ vs exponential.',
      'Tanks-in-series N: 1=CSTR, ∞=PFR.',
    ],
    revision: {
      remember: 'PFR < CSTR volume (1st order); CSTR = outlet; RTD ideal forms.',
      mistakes: ['CSTR designed at inlet concentration.'],
      summary: 'Ideal reactors + design equations + RTD + non-ideal models.',
    },
    related: ['bae-cstr', 'trp-control', 'mic-sterilization'],
  },
  {
    id: 'trp-numericals',
    subject: 'transport-processes',
    name: 'GATE Focus: Transport Numericals',
    level: 4,
    priority: 'high',
    ord: 7,
    short: 'The transport calculations that appear in GATE.',
    basic: {
      what: 'GATE transport = Re + pressure drop (both regimes) + heat (U, LMTD) + mass (α, Fenske) + control (PID, FOPDT) + reactor (PFR/CSTR, RTD).',
      why: 'Formula-driven, high ROI per practice hour.',
      how: 'Pattern 1: compute Re → pick flow regime → pressure drop. Pattern 2: heat exchanger U + LMTD → Q. Pattern 3: distillation α → Fenske stages. Pattern 4: reactor volume for given X.',
      where: 'GATE BT paper.',
    },
    college: [
      'Re = ρvD/μ; then Hagen (laminar) or Darcy (turbulent).',
      'Q = U·A·LMTD; 1/U = ΣR.',
      'Fenske: N_min = ln(sep)/ln α.',
      'PFR V = (v0/k)ln(1/(1−X)); CSTR V = v0X/k.',
      'PID: Kp/Ki/Kd roles; FOPDT K, τ, θ.',
    ],
    advanced: [
      'Combined: sterilisation tubular (PFR) + D-value residence time.',
      'Bioreactor: OTR = kLa(C*−CL) = qO2·X (O2 balance).',
    ],
    gate: {
      highYield: [
        'All six pattern families with unit discipline.',
        'Flow-regime decision (Re) before pressure drop.',
        'Reactor volume comparison.',
      ],
      traps: [
        'Wrong regime → wrong pressure-drop equation.',
        'CSTR vs PFR volume (PFR smaller for 1st order).',
        'U decreases with fouling (R_f added).',
      ],
    },
    examples: [
      'Re = 5000 (turbulent), Darcy f=0.02, L/D=100, ρv²/2=500 Pa → ΔP = 0.02×100×500 = 1000 Pa.',
      'First-order, X=0.9, k=0.5 s\u207b\u00b9, v0=10 L/s: PFR V = (v0/k)\u00b7ln(1/(1\u2212X)) = 20\u00d7ln(10) \u2248 46 L; CSTR V = v0\u00b7X/(k(1\u2212X)) = 9/0.05 = 180 L \u2192 PFR much smaller, as expected for 1st-order kinetics.',
    ],
    formulas: [
      { name: 'CSTR (1st order, corrected)', expr: 'V = v0·X/(k(1−X))' },
    ],
    keyPoints: [
      'Re first, then regime-specific equation.',
      'PFR < CSTR volume (1st order, positive X).',
      'U ↓ with fouling.',
      'Unit discipline throughout.',
    ],
    revision: {
      remember: 'Re→regime→ΔP; U·A·LMTD; Fenske; PFR<CSTR; PID roles.',
      mistakes: ['Regime swap; CSTR volume formula (has (1−X) in denominator).'],
      summary: 'Transport GATE = six formula families with regime/unit discipline.',
    },
    related: ['trp-momentum', 'trp-heat', 'trp-mass', 'trp-control', 'trp-reactors'],
  },
];

export const ALL = [...TOPICS_PLB, ...TOPICS_PRO, ...TOPICS_RDT, ...TOPICS_TRP];
